// Page copy — CONFIG + TYPE_META + VENUES
const CONFIG = {
  kicker: "Boston Tech Week · Venue Scout",
  title: "Boston — Venue Options",
  subtitle: "Event-capable cafes & event spaces in Kendall Sq / Seaport / Downtown — for a Oct 2, 2026 bilingual tech-week coffee/hack event (~50–200 people). Overlaps Boston AI Week (Sep 24–Oct 2 centered in the Seaport).",
  extraStat: {"n":"Oct 2","l":"Boston event date, 2026"},
  footnotes: [
    "<b>Neighborhood analysis:</b> Kendall Sq/MIT (Microsoft NERD, MIT IHQ, The Foundry, CIC 1 Broadway) is the bilingual AI/home-base; Seaport (Island Creek Raw Bar anchoring AI Week parties, 88 Seaport, Westin) is the event-district; Downtown/Fidi (CIC Boston at 50 Milk St, Venture Lane at 55 Court) conveniently bridges the two.",
    "<b>Gone / don't route inquiries here:</b> 45 closure/discards logged — District Hall (75 Northern Ave) has been shuttered since 2023; do not plan around it.",
  ],
  provenance: "Researched Aug 2026 · EN · 26 → 26 shipped after contract (drops: none) · Capacities published or estimated.",
};

const TYPE_META = {
  coffee: { label: "Coffee shop", icon: "☕" },
  cowork: { label: "Coworking / event space", icon: "🏢" },
};

const VENUES = [
  {
    "k": "vester_cafe_cambridge",
    "name": "Vester Cafe — Cambridge (Kendall Square)",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "coffee",
    "addr": "73 Ames St, Cambridge, MA 02142",
    "cap": "~<b><b>80</b></b> seated / <b>300</b>+ catered standing (est; site advertises corporate catering for 300+ and full-venue buyouts)",
    "flag": "dedicated",
    "link": "https://vestercafe.com/catering",
    "linkText": "Catering + Events",
    "email": "catering@vestercafe.com",
    "note": "Female/minority-owned international cafe purpose-built for remote work and networking in the heart of Kendall Sq; dedicated catering/events page explicitly offers full buyouts ('Make VESTER exclusively yours') — the closest match to a bilingual coffee-takeover hack day in the neighborhood.",
    "img": "https://images.squarespace-cdn.com/content/v1/65daae8958d6ef031fb95034/b4936dd8-2f4f-4305-ac9a-e3315d7952e6/_MG_7061.jpeg",
    "alt": "Bright modern cafe interior with communal tables at Vester Cambridge",
    "top": true
  },
  {
    "k": "venture_caf_at",
    "name": "Venture Café at CIC Cambridge (One Broadway) — tour-trace seed via CreativeMornings",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "coffee",
    "addr": "1 Broadway, 5th Floor, Cambridge, MA 02142",
    "cap": "Venture Café space <b><b>150</b></b>; The Lookout rooftop <b>150</b>; Havana <b>80</b>; pairable breakouts, spaces for 2-150+",
    "flag": "dedicated",
    "link": "https://cic.com/cambridge/events-spaces",
    "linkText": "CIC Cambridge Event Spaces",
    "email": "events@cic.com",
    "note": "CreativeMornings/Boston hosted its Nov 2025 breakfast lecture at CIC Cambridge (1 Broadway) — proven coffee-and-100+-crowd room-shape fit; the wood-paneled Venture Café space is literally Kendall Sq's weekly innovation-coffee gathering spot (Thursday Gatherings, 20K visitors/yr), with terrace, bar space, breakouts, and translation services via LinguaSmart for a bilingual tech-week day.",
    "img": "https://venturecafecambridge.org/wp-content/uploads/sites/6/2021/05/IMG_1861-1.jpg",
    "alt": "Venture Café Cambridge Thursday Gathering crowd at CIC",
    "top": false
  },
  {
    "k": "the_foundry",
    "name": "The Foundry",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "coffee",
    "addr": "101 Rogers St, Cambridge, MA 02142",
    "cap": "Community Hall <b><b>175</b></b> seated / <b>300</b> standing; STEAM Set performance space <b>115</b> seated / <b>150</b> standing; full building <b>400</b>",
    "flag": "dedicated",
    "link": "https://www.cambridgefoundry.org/event-rentals",
    "linkText": "Event Rentals",
    "email": null,
    "note": "1890 industrial creative hub 0.4 mi from Kendall/MIT T actively recruiting a cafe operator; maker-space DNA (Design Lab built for hackathons), sliding-scale pricing for community events, and a three-story atrium Community Hall that fits the 50-200 hack-day band at public-event rates.",
    "img": "https://cdn.prod.website-files.com/6266e76b1797370598592b60/63952408e4a413f5de1a01e8_Community%20Hall%2008.22.22.jpg",
    "alt": "The Foundry Community Hall tall wood-beam interior",
    "top": false
  },
  {
    "k": "area_four_kendall",
    "name": "Area Four Kendall Square / A4 Café",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "coffee",
    "addr": "500 Technology Square, Cambridge, MA 02139",
    "cap": "Private room <b><b>40</b></b> cocktail / <b>20</b> seated (published); full cafe+pizza-bar buyout larger but unpublished — inquire",
    "flag": "dedicated",
    "link": "https://www.areafour.com/private-events-venue/kendall-square",
    "linkText": "Kendall Square Private Events",
    "email": "Victoria@AreaFour.com",
    "note": "Technology Square cafe-bar directly facing the MIT campus edge with an on-site A4 Café for coffee service, two private rooms and outdoor space; published private-room capacity (40 cocktail) sits below the 50-200 band, so this works only as a full-venue buyout play — events coordinator published by name.",
    "img": "https://images.getbento.com/accounts/6797956624a9674f3b0f27765887f7df/media/images/10177Area_Four_Cambridge_Interior_2_Melissa_Ostrow.jpg?w=1800&fit=max&auto=compress,format&cs=origin&h=1800",
    "alt": "Area Four Cambridge dining room at 500 Technology Square",
    "top": false
  },
  {
    "k": "the_platform_kendall",
    "name": "The Platform Kendall (Takeda Theater + Tempo Stage + Commons)",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "cowork",
    "addr": "585 Third St, Cambridge, MA 02142",
    "cap": "<b><b>404</b></b> seated (Takeda Theater) / <b>125</b> (Tempo Stage) / <b>150</b> auditorium or <b>50</b> seated (Rehearsal Studio) + ground-floor commons and Bar Tempo cafe",
    "flag": "dedicated",
    "link": "https://www.theplatformkendall.org/rental-info",
    "linkText": "Rental Info — The Platform",
    "email": null,
    "note": "Brand-new 45,000-sq-ft cultural hub (BioMed Realty + Global Arts Live) that just opened in Kendall Square; can easily handle a 200-person bilingual coffee/hack day between the Tempo Stage commons and Rehearsal Studio, with Bar Tempo cafe on the ground floor. Rental inquiry form + 617.395.4323 (no public events email published).",
    "img": "https://www.theplatformkendall.org/wp-content/uploads/2026/05/WP-crowd2.jpg",
    "alt": "Takeda Theater auditorium and commons at The Platform Kendall",
    "top": true
  },
  {
    "k": "thos_cambridge",
    "name": "Æthos Cambridge",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "cowork",
    "addr": "1 Broadway, 7th Floor (CIC), Cambridge, MA 02142",
    "cap": "~<b><b>120</b></b> standing / ~<b>80</b> seated (est; clubhouse floor at CIC)",
    "flag": "contact",
    "link": "https://aethos.org",
    "linkText": "aethos.org",
    "email": "hello@aethos.org",
    "note": "AI-native members' clubhouse inside CIC in the heart of Kendall — built precisely for AI-engineer coffee/hack crowds. Tour-trace seed via AI Tinkerers Boston (Aug 2024 meetup hosted here): proven builder-event history. Room-shape fit: open clubhouse + cafe layout is a natural 50-150 hack-day room; contact hello@aethos.org for private takeovers.",
    "img": "https://aethos.org/uploads/images/1776532158173-1867hwop15b.png",
    "alt": "Æthos Cambridge clubhouse community gathering",
    "top": false
  },
  {
    "k": "venture_caf_cambridge",
    "name": "Venture Café Cambridge at CIC One Broadway",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "cowork",
    "addr": "One Broadway, 5th Floor, Cambridge, MA 02142",
    "cap": "~<b><b>200</b></b> standing Thursday Gathering (est; serves 20K attendees/year across free weekly programs)",
    "flag": "contact",
    "link": "https://venturecafecambridge.org",
    "linkText": "venturecafecambridge.org",
    "email": "hello@venturecafecambridge.org",
    "note": "Weekly free innovation gathering on CIC's 5th floor in Kendall — the existing room already runs the exact coffee-and-mingle tech-crowd shape we need. Can sponsor/take over a Thursday Gathering or book a custom package through CIC; email for collaboration and sponsorship.",
    "img": "https://venturecafecambridge.org/wp-content/uploads/sites/6/2021/05/IMG_1861-1.jpg",
    "alt": "Venture Café Cambridge Thursday Gathering crowd at CIC",
    "top": false
  },
  {
    "k": "greentown_labs_town",
    "name": "Greentown Labs (Town Green)",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "cowork",
    "addr": "444 Somerville Ave, Somerville, MA 02143",
    "cap": "<b><b>500</b></b> standing (Town Green event space; published)",
    "flag": "contact",
    "link": "https://greentownlabs.com/greentown-boston",
    "linkText": "Greentown Boston",
    "email": "kwilson@greentownlabs.com",
    "note": "World's largest climatetech incubator just over the Cambridge line near Union Sq; Town Green + roof deck regularly host demo days and hackathons (~300 events/yr). Easily absorbs a 200-person bilingual tech-week coffee/hack; reach events team for host/rental inquiry.",
    "img": "https://greentownlabs.com/wp-content/uploads/2025/05/042425-greentown-labs-01-037-copy-1536x1024.jpg",
    "alt": "Greentown Labs Town Green event space and prototyping floor",
    "top": false
  },
  {
    "k": "canalside_food_drink",
    "name": "CanalSide Food + Drink at CambridgeSide",
    "area": "Kendall Square / MIT (Cambridge)",
    "type": "cowork",
    "addr": "100 CambridgeSide Place, Cambridge, MA 02141",
    "cap": "~<b><b>75</b></b> semi-private C-Side lounge (published) / ~<b>200</b> full food hall + canal-side patio buyout (est)",
    "flag": "dedicated",
    "link": "https://www.cambridgeside.com/private-events",
    "linkText": "CambridgeSide — Private Events",
    "email": null,
    "note": "Waterfront food hall inside CambridgeSide with a dedicated private-events program: C-Side Bar/Viewing Corner, Community Meeting Room, outdoor patio, and full-hall buyouts. Casual coffee/Latin-food-hall energy suits a bilingual tech-week crowd; inquiry form on page, 617.621.8666.",
    "img": "https://cdn-files.eu.placewise.com/f/CKSFPRCIBhoTY21zX2NvbXBvbmVudF9pbWFnZSIVaWQtMTc2MTYwNjMxMzcyMC0xMTIwONe-q0wFNKlYMYpeykCBuNphdU-4?transform=output=format:webp,quality:80/resize=width:1920,height:1920,fit:clip",
    "alt": "CanalSide food hall interior with canal views at CambridgeSide",
    "top": false
  },
  {
    "k": "district_hall",
    "name": "District Hall",
    "area": "Seaport District (Boston)",
    "type": "coffee",
    "addr": "75 Northern Avenue, Boston, MA 02210",
    "cap": "Lounge <b><b>150</b></b> standing; Full Assembly <b>200-250</b>; Full building <b>450</b>",
    "flag": "dedicated",
    "link": "https://districthallboston.org/host-an-event",
    "linkText": "Book the Space",
    "email": null,
    "note": "Boston's purpose-built innovation 'living room' — coffee-shop vibe public lounge on weekdays + movable-wall Assembly bays that hosted hundreds of hack nights, demo days, and builder meetups; plug-and-play power/projectors/Bose AV, on-mission startup discounts, caters through Briar Events. Tour-trace adjacent: the Seaport anchor for Boston AI Tinkerers / hackathon culture. (Note: onsite café Gather + Brew reached end-of-lease in 2026 per Briar Group, so F&B is catering-based now — verify operationally before booking.)",
    "img": "https://images.squarespace-cdn.com/content/v1/61eece2d4fbafa01980fb0c8/6e2f7799-f3e9-46e2-bcb5-4886c37dc263/CiscoSeaport-2-sm.jpg",
    "alt": "Wide-angle view of District Hall Assembly hall with movable furniture and IdeaPaint walls",
    "top": true
  },
  {
    "k": "tatte_bakery_caf",
    "name": "Tatte Bakery & Café | Pier 4",
    "area": "Seaport District (Boston)",
    "type": "coffee",
    "addr": "200 Pier 4 Blvd, Boston, MA 02210",
    "cap": "~<b><b>80</b>-120</b> indoor + harbor-view patio (est)",
    "flag": "contact",
    "link": "https://tattebakery.com/locations/ma/boston/200-pier-4-blvd",
    "linkText": "Tatte Pier 4 location page",
    "email": "contact@tattebakery.com",
    "note": "Boston-born specialty coffee + bakery anchor with sweeping harbor views and ~3,600 sqft footprint on Pier 4's ground floor; Tatte's catering line (617-945-1205) books groups, and the size + specialty-coffee focus make it the strongest coffee-native Seaport room for a daytime hack-coffee format. Walk-in only by policy, so evening partial buyout via contact@tattebakery.com is the realistic ask.",
    "img": "https://a.mktgcdn.com/p/zDjgJm0zXf8RhO0-3f-PLaJVnWZTYs2GU9Peaxqbw1c/500x1000.jpg",
    "alt": "Interior of Tatte Pier 4 with pastry case and floor-to-ceiling harbor windows",
    "top": false
  },
  {
    "k": "daily_provisions_seaport",
    "name": "Daily Provisions Seaport",
    "area": "Seaport District (Boston)",
    "type": "coffee",
    "addr": "200 Seaport Blvd, Suite 0101, Boston, MA 02210",
    "cap": "~<b><b>60</b>-100</b> (est; opened spring 2026, footprint not yet published)",
    "flag": "contact",
    "link": "https://www.dailyprovisions.co/location/seaport",
    "linkText": "Daily Provisions Seaport location",
    "email": "info@dailyprovisions.co",
    "note": "Danny Meyer / Union Square Hospitality Group's all-day café that just opened on Commonwealth Pier (steps from ICA + BCEC); crullers + coffee morning trade, evening beer/wine crowd, USHG hospitality pedigree — group buyout email goes through the home office (info@dailyprovisions.co). Best for a <100-person format or as catering anchor for a nearby room.",
    "img": "https://images.getbento.com/accounts/421fdbfaa020a606991e0319ff8084f3/media/images/54101081825_dailyprov_dupont_lifestyle-0020.JPG?w=1200&fit=crop&auto=compress,format&cs=origin&h=600",
    "alt": "Daily Provisions cafe interior, Seaport",
    "top": false
  },
  {
    "k": "travelmug_caf_at",
    "name": "Travelmug Café at GrubStreet (Fabulist Café)",
    "area": "Seaport District (Boston)",
    "type": "coffee",
    "addr": "50 Liberty Dr, Boston, MA 02210 (inside GrubStreet Center for Creative Writing)",
    "cap": "~<b><b>50</b>-80</b> café + Writers' Stage event space (est)",
    "flag": "contact",
    "link": "https://grubstreet.org/about/fabulist-cafe",
    "linkText": "GrubStreet's Café / Fabulist",
    "email": null,
    "note": "New (2025-26) coffee shop inside Seaport's creative-writing nonprofit, co-run with Travelmug; harbor-view tables, next door to Porter Square Books, with GrubStreet's Writers' Stage used for monthly literary events — already set up for seated talk + reception formats. Café + stage combo fits an intimate builder coffee day of ~50-80; booking goes through GrubStreet's main line (617-695-0075).",
    "img": "https://media.thebostoncalendar.com/images/q_auto,fl_lossy/v1746883674/h8hzowhbxkajdx3trz71/travel-mug-cafe.jpg",
    "alt": "Travelmug Cafe inside GrubStreet Fabulist",
    "top": false
  },
  {
    "k": "district_hall_boston",
    "name": "District Hall Boston",
    "area": "Seaport District (Boston)",
    "type": "cowork",
    "addr": "75 Northern Ave, Boston, MA 02210",
    "cap": "Assembly: <b><b>200</b></b> seated theater / <b>250</b> standing; full building <b>450</b>; free cowork lounge + onsite Brew coffee bar",
    "flag": "dedicated",
    "link": "https://districthallboston.org/host-an-event",
    "linkText": "Book the Space",
    "email": null,
    "note": "Boston's free-standing public innovation center (Venture Cafe Foundation nonprofit) in the heart of Seaport — it literally runs hackathons, with a free public cowork lounge, writable walls, integrated power worktables, onsite Brew coffee bar, hourly rates from $115/bay, and nonprofit/startup site-fee discounts. Exact match for a 50-200 bilingual coffee/hack day. Room-shape fit note: AI Tinkerers Boston's own chapter quote calls this class of innovation-center space 'nearly perfect' for builder meetups — District Hall is that archetype in Seaport proper.",
    "img": "https://districthallboston.org/files/wp-content/uploads/2018/07/2017.02.26_dh-setup-shots_001_1600x776_optimized-2.jpg",
    "alt": "Wide Assembly hall with high-top tables and string lights",
    "top": true
  },
  {
    "k": "bsa_space_boston",
    "name": "BSA Space (Boston Society for Architecture)",
    "area": "Seaport District (Boston)",
    "type": "cowork",
    "addr": "290 Congress Street, Suite 200, Boston, MA 02210 (Atlantic Wharf)",
    "cap": "Full Gallery <b><b>500</b></b> reception; Salt Gallery <b>100</b> theater / <b>100</b> reception; Harbor Room <b>50</b> theater; Channel Room <b>40</b> theater",
    "flag": "dedicated",
    "link": "https://www.architects.org/about/rentals",
    "linkText": "Rent BSA Space",
    "email": "rentals@architects.org",
    "note": "Hoeeler + Yoon-designed gallery on the Fort Point Channel edge of Seaport — daylit, exhibition-lined space with ceiling projectors, Bose sound, whiteboards, catering kitchenette, and a published rates schedule; rotating architecture exhibits double as decor for a builder-crowd hack day.",
    "img": "https://bsa-prod.nyc3.cdn.digitaloceanspaces.com/uploads/_auto1800/11360/BSA-8212.webp",
    "alt": "Full BSA Gallery with Fort Point Channel views",
    "top": false
  },
  {
    "k": "the_exchange_conference",
    "name": "The Exchange Conference Center",
    "area": "Seaport District (Boston)",
    "type": "cowork",
    "addr": "212 Northern Ave, Boston, MA 02210 (Boston Fish Pier)",
    "cap": "Exchange Hall <b><b>180</b></b> seated / <b>300</b> standing; full venue up to ~<b>300</b> reception",
    "flag": "dedicated",
    "link": "https://exchangeconferencecenter.com/",
    "linkText": "Event and Conference Center",
    "email": "info@emwcatering.com",
    "note": "Historic Fish Exchange hall on the working fish pier — floor-to-ceiling harbor views, full liquor license, A/V, and exclusive in-house catering (East Meets West) that runs the venue; published event-planner contacts and a corporate events track. Swap assembly-line fish history for a hackathon.",
    "img": "https://exchangeconferencecenter.com/wp-content/uploads/2023/12/longview-1024x768.jpg",
    "alt": "Long view of Exchange Hall interior with harbor windows",
    "top": false
  },
  {
    "k": "aloft_boston_seaport",
    "name": "Aloft Boston Seaport District",
    "area": "Seaport District (Boston)",
    "type": "cowork",
    "addr": "401-403 D Street, Boston, MA 02210",
    "cap": "Mann Ballroom <b><b>480</b></b> theater / <b>400</b> reception; Summer Ballroom <b>200</b> theater; 9 event rooms total (~9,400 sq ft)",
    "flag": "dedicated",
    "link": "https://www.marriott.com/en-us/hotels/bosal-aloft-boston-seaport-district/events/",
    "linkText": "Event & Meeting Spaces",
    "email": null,
    "note": "Full Marriott-published room/dimension chart on its events page and 330-room room block next door to BCEC; hosted the Nymbl AI Hackathon, so a laptop-and-lanyard day is proven here. WXYZ Bar handles the after-hours coffee-to-cocktail shift.",
    "img": "https://img.partyslate.com/photos/3141268/photo-1e72205b-342b-4162-b338-c1a7cf60cb90.jpeg?tr=w-640",
    "alt": "Aloft Mann Ballroom set for a reception",
    "top": false
  },
  {
    "k": "seaport_hotel_boston",
    "name": "Seaport Hotel Boston",
    "area": "Seaport District (Boston)",
    "type": "cowork",
    "addr": "1 Seaport Lane, Boston, MA 02210",
    "cap": "Plaza Ballroom <b><b>700</b></b> theater / <b>750</b> reception; Seaport Ballroom <b>420</b> theater / <b>450</b> reception; 27,000 sq ft total event space",
    "flag": "dedicated",
    "link": "https://www.seaportboston.com/meeting-events/venues",
    "linkText": "Meeting & Event Venues",
    "email": "seaportsales@seaportboston.com",
    "note": "Independent waterfront hotel with a public capacity chart across 13 spaces, harbor-view ballrooms, on-site catering/AV, and a direct meetings sales inbox — a safe scale-up option if the hack day pushes past 200.",
    "img": "https://assets.milestoneinternet.com/cdn-cgi/image/f=auto/seaport-hotel-and-world-trade-center-parent/seaport-hotel-boston/siteimages/meetings-seaport-ballroom-reception.jpg?width=1800&height=600",
    "alt": "Seaport Hotel Boston Plaza Ballroom",
    "top": false
  },
  {
    "k": "high_street_place",
    "name": "High Street Place (home of Gracenote Coffee, Wine & Coffee Cocktails)",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "coffee",
    "addr": "100 High St, Boston, MA 02110",
    "cap": "Atrium up to <b><b>100</b></b>; Vinyl Store + Nano Patio combined <b>100</b>; Garden Patio <b>48</b> seated / <b>55</b> standing; full food-hall buyout ~<b>200+</b> (est, quote-based)",
    "flag": "dedicated",
    "link": "https://www.highstreetplace.com/private-events",
    "linkText": "High Street Place Private Events",
    "email": "events@highstreetplace.com",
    "note": "Best coffee-shaped room in the FiDi: Gracenote Coffee runs the espresso/coffee-cocktail bar on site (open to 10pm Thu-Sat), and the hall has four bookable semi-private zones plus buyout, 80-seat patio, 28ft LED wall and full A/V — a daytime coffee/hack day plugs straight into existing barista service. Fits 50-200 by choosing Atrium, patio combo, or full buyout.",
    "img": "https://www.highstreetplace.com/wp-content/uploads/2021/09/LIPBN_FH-03_Main-Entry-1a_200828-1024x682.jpg",
    "alt": "Wide shot of the High Street Place atrium entrance with green wall and food-hall seating",
    "top": true
  },
  {
    "k": "cic_boston_cambridge",
    "name": "CIC Boston (Cambridge Innovation Center) — Venture Café hall, 50 Milk St",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "coffee",
    "addr": "50 Milk St, Boston, MA 02109",
    "cap": "CIC publishes event spaces for <b><b>20–400</b></b> across campuses; Boston rooms ~<b>50–150</b> (est per room size, quote via Events team)",
    "flag": "dedicated",
    "link": "https://cic.com/event-spaces",
    "linkText": "CIC Event Spaces (Boston campus)",
    "email": null,
    "note": "The brief's anchor building: on-site Events team, catered with premium coffee/tea service on every floor, Venture Café-style weekly innovation programming in the same building, and a tech crowd already in-house — a bilingual tech-week coffee/hack day is native programming here. Impact Hub Boston previously ran community events from this address. Non-members can book.",
    "img": "https://cic.com/wp-content/uploads/2026/04/Venture-Cafe-2-scaled.webp",
    "alt": "Venture Café event space with open gathering area at a CIC campus",
    "top": false
  },
  {
    "k": "sip_cafe",
    "name": "Sip Cafe",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "coffee",
    "addr": "0 Post Office Square, Boston, MA 02110",
    "cap": "~<b><b>40</b></b> seated / ~<b>80</b> standing (est; hosts wedding receptions and private functions)",
    "flag": "dedicated",
    "link": "http://www.sipboston.com/events",
    "linkText": "Sip Cafe Events",
    "email": "catering@sipboston.com",
    "note": "Independent downtown coffee house one block from 50 Milk St that explicitly books private events, pours beer/wine alongside its coffee bar, and stays open to 8pm weekdays — sized for the 50-80 end of the hack-day crowd rather than a full 200. English-first, intimate room with counter service and event testimonials on the page.",
    "img": "http://www.sipboston.com/images/gallery/full-size/sip-cafe-boston-tables.jpg",
    "alt": "Sip Cafe interior with cafe tables and chairs",
    "top": false
  },
  {
    "k": "george_howell_coffee",
    "name": "George Howell Coffee — The Godfrey Hotel (Downtown Crossing)",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "coffee",
    "addr": "505 Washington St, Boston, MA 02111",
    "cap": "~<b><b>40</b></b> seated in-cafe (est); after-hours buyout capacity by arrangement (est)",
    "flag": "contact",
    "link": "https://georgehowellcoffee.com/pages/the-godfrey-hotel",
    "linkText": "George Howell at the Godfrey Hotel",
    "email": "godfrey@georgehowellcoffee.com",
    "note": "Boston's most storied specialty-coffee flagship (roasting since 1975), ground floor of the Godfrey in Downtown Crossing with the 'Exploratorium' retail/class area built for programming — weekly public cupping classes prove event-hosting behavior. Cafe closes 6:30pm, so a hack day books as an after-hours buyout through the published cafe email.",
    "img": "https://georgehowellcoffee.com/cdn/shop/files/97-DSC01433_resized_b6e15395-54d5-44fc-84e7-67710040dc38.jpg?v=1773677278&width=1000",
    "alt": "George Howell Coffee cafe interior with espresso bar",
    "top": false
  },
  {
    "k": "cic_boston_cambridge_50milk",
    "name": "CIC Boston (Cambridge Innovation Center)",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "cowork",
    "addr": "50 Milk St, Boston, MA 02109",
    "cap": "Conference rooms to <b><b>16</b></b> published; campus event hosting via CIC events team — ~<b>100</b>+ in shared/lounge floors (est)",
    "flag": "dedicated",
    "link": "https://cic.com/events/boston",
    "linkText": "CIC Meetings & Events (Boston + Cambridge)",
    "email": null,
    "note": "Cell's namesake anchor in the FiDi: five-floor innovation campus that already runs Thursday Gathering-style public programming, coffee hours and client events, with an on-site events team and 50+ conference rooms as breakouts. Tour-trace fit: CIC's sibling campuses host AI Tinkerers-style builder events weekly, so the staff muscle for a 50-200 coffee/hack day exists; confirm the 50M event floor when inquiring.",
    "img": "https://cic.com/wp-content/uploads/2026/04/BOS-50M-Lounge_2020.webp",
    "alt": "Shared lounge with soft seating inside CIC Boston at 50 Milk Street",
    "top": true
  },
  {
    "k": "convene_one_boston",
    "name": "Convene One Boston Place",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "cowork",
    "addr": "201 Washington St, Boston, MA 02108",
    "cap": "Up to <b><b>400</b></b> guests venue-wide; The Gallery <b>172</b>, The Forum <b>172</b>, The Hub <b>161</b> + breakout rooms",
    "flag": "dedicated",
    "link": "https://convene.com/locations/boston/one-boston-place",
    "linkText": "Convene One Boston Place — Meetings & Events",
    "email": null,
    "note": "Purpose-built 15,000 sq ft event floor in the heart of the FiDi with in-house catering (coffee service built in), white-box rooms for branding, on-site A/V team and a private outdoor terrace — the safest capacity match for a 50-200 bilingual coffee/hack day near Downtown Crossing.",
    "img": "https://images.ctfassets.net/rpinqlxtcitg/5fo07BrCQkK4xOOPPtDIx0/c9447a2860a8b45292ee3f30cb3d78ce/One_Boston_Place_-_Gallery.jpg",
    "alt": "Wide Gallery event room at Convene One Boston Place",
    "top": false
  },
  {
    "k": "wework_33_arch",
    "name": "WeWork 33 Arch Street",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "cowork",
    "addr": "33 Arch St, Boston, MA 02110",
    "cap": "~<b><b>80</b></b>-<b>100</b> standing in converted lounge event space (est; no published figure)",
    "flag": "dedicated",
    "link": "https://www.wework.com/buildings/33-arch-st--boston--MA",
    "linkText": "WeWork 33 Arch Street — Event Spaces",
    "email": null,
    "note": "Downtown tower between FiDi and Downtown Crossing with a bookable dedicated event space (sound system + lighting controls), cafe-style common areas and an events-active community team — reviewers repeatedly praise its hosted events. Good budget-flex option for a casual hack-day format.",
    "img": "https://ctfassets.imgix.net/vh7r69kgcki3/1CY7WxrVXzi713zq1ffCCc/db518aa612d78721d62088dd1786e219/event_space.webp",
    "alt": "WeWork event space lounge with rows of chairs facing a screen",
    "top": false
  },
  {
    "k": "workbar_downtown",
    "name": "Workbar Downtown",
    "area": "Downtown Boston / Financial District (incl. CIC Boston @ 50 Milk St, Downtown Crossing edge)",
    "type": "cowork",
    "addr": "24 School St, 2nd Floor, Boston, MA 02108",
    "cap": "~<b><b>200</b></b> seated in large event space; <b>50</b> in intimate event space (est, via venue marketplace listing; 17,000 sq ft floor)",
    "flag": "contact",
    "link": "https://www.workbar.com/locations/downtown",
    "linkText": "Workbar Downtown — Coworking & Event Space",
    "email": "downtown@workbar.com",
    "note": "Historic 24 School St building on the Downtown Crossing edge, steps from Park Street / Downtown Crossing T, with an event-space amenity, fully stocked cafe zone and custom events programming — a natural coffee/hack-day room with a大楼 of natural light and Downtown Crossing foot traffic outside.",
    "img": "https://www.workbar.com/hs-fs/hubfs/locations/downtown/Workbar_ss_10%20(1).jpg?width=900",
    "alt": "Workbar Downtown coworking area with high exposed ceilings",
    "top": false
  }
];
