// Page copy
const CONFIG = {
  kicker: "LA Tech Week · ComputeCafe",
  title: "LA Tech Week — Venue Options",
  subtitle: "Large coffee shops & coworking spaces in Santa Monica and Venice that can host an all-day, " +
            "Tech Week-style coffee event (~50–200+ people). Links point to each venue's private-events " +
            "page or best booking contact.",
  extraStat: { n: "Oct 12–18", l: "LA Tech Week 2026 dates" },
  footnotes: [
    "<b>Gone since last Tech Week — don't route inquiries here:</b> Rose Café (closed Dec 2024), NeueHouse Venice Beach (closed Sept 2025), Cross Campus (closed — its 929 Colorado space is now BLANKSPACES), Philz Santa Monica, and Interstellar. Groundwork's remaining SM/Venice shops and Menotti's are too small to host.",
    "<b>Pairing tip:</b> going with a coworking venue? goodboybob, Intelligentsia, and Menotti's all run mobile espresso / coffee-truck service you can bring in-house.",
  ],
  provenance: "Researched & links verified Aug 6, 2026 · LA Tech Week 2026: Oct 12–18 (SF Tech Week runs Oct 5–11) · " +
              "Photos load from each venue's own website; a placeholder appears where no photo was published. " +
              "Capacities are published or estimated figures — confirm when booking.",
};

const TYPE_META = {
  coffee: { label: "Coffee shop", icon: "☕" },
  cowork: { label: "Coworking",  icon: "🏢" },
};

const VENUES = [
  // ---------- SANTA MONICA · COFFEE ----------
  {k:"goodboybob", name:"goodboybob coffee roasters", area:"Santa Monica", type:"coffee", top:true,
   addr:"2058 Broadway, Santa Monica", lat:34.0281368, lng:-118.4761783, cap:"Espresso service up to <b>200</b> · patio + studio",
   flag:"dedicated", link:"https://goodboybob.com/pages/events", linkText:"Events page", email:null,
   note:"Best coffee-brand venue in SM — tiered patio + marble bar on Tool of North America's creative campus, with an adjoining screening/VR studio for programming.",
   img:"https://goodboybob.com/cdn/shop/files/goodboybob-Luft10-hires-np-5808.jpg?v=1751565817&width=1200", alt:"goodboybob café and event space"},
  {k:"bluestone", name:"Bluestone Lane", area:"Santa Monica", type:"coffee",
   addr:"631 Wilshire Blvd, Santa Monica", lat:34.0214021, lng:-118.495846, cap:"~<b>50–100</b> · café + patio hire",
   flag:"dedicated", link:"https://bluestonelane.com/private-events/", linkText:"Private events", email:null,
   note:"Large corner café with a sunny patio. The most turnkey booking of any coffee shop here — formal corporate-events program, books via TripleSeat.",
   img:"https://bluestonelane.com/wp-content/uploads/2018/03/BL-SantaMonica-1610x600.jpg", alt:"Bluestone Lane Santa Monica interior"},
  {k:"urth", name:"Urth Caffé", area:"Santa Monica", type:"coffee",
   addr:"2327 Main St, Santa Monica", lat:34.0043977, lng:-118.4858107, cap:"<b>100+</b> footprint · no published buyout program",
   flag:"contact", link:"https://www.urthcaffe.com/catering", linkText:"Catering dept", email:"catering@urthcaffe.com",
   note:"One of the biggest café footprints in SM — huge garden patio + full dining room. Go through the catering director for anything event-shaped.",
   img:"https://popmenucloud.com/cdn-cgi/image/width=1200,height=630,format=auto,fit=cover/lzaqjwcu/e7ac944a-6366-40b0-9f67-4ea61593b6cc.jpg", alt:"Urth Caffé Santa Monica"},
  {k:"dogtown", name:"Dogtown Coffee", area:"Santa Monica", type:"coffee",
   addr:"2003 Main St, Santa Monica", lat:34.0071466, lng:-118.4886953, cap:"~<b>50–100</b> · closes 2pm, extend privately",
   flag:"contact", link:"https://www.dogtowncoffee.com/", linkText:"Site + GM contact", email:"gm@dogtowncoffee.com",
   note:"The landmark Zephyr/Dogtown skate building — big open room that already runs live-music events, so crowd + AV logistics exist.",
   img:"https://www.dogtowncoffee.com/wp-content/uploads/2022/10/Dogtown-Main.jpg", alt:"Dogtown Coffee on Main Street"},
  {k:"bondi", name:"Bondi Harvest", area:"Santa Monica", type:"coffee",
   addr:"1814 Berkeley St, Santa Monica", lat:34.0314955, lng:-118.462814, cap:"~<b>50–100</b> · easiest full-day takeover",
   flag:"contact", link:"https://bondiharvest.cafe/", linkText:"Site + contact", email:"sabrina@bondiharvest.com",
   note:"Roomy Aussie café in the warehouse district east of 26th — low tourist traffic and easy parking make it the most flexible all-day option.",
   img:"https://bondiharvest.cafe/files/wp-content/uploads/2016/03/restaurant_1000x500_9.jpg", alt:"Bondi Harvest interior"},
  {k:"huckleberry", name:"Huckleberry Bakery & Café", area:"Santa Monica", type:"coffee",
   addr:"1014 Wilshire Blvd, Santa Monica", cap:"<b>Partial-day</b> — private parties eve only",
   flag:"dedicated", link:"https://www.huckleberrycafe.com/cateringandevents/", linkText:"Catering & events", email:"catering@huckleberrycafe.com",
   note:"Big bakery-café (Rustic Canyon family) with a real events program — but private parties run late-afternoon/evening, so it's an anchor, not an all-day host.",
   img:"https://www.huckleberrycafe.com/wp-content/uploads/2023/07/Huckleberry-shop-Santa-Monica.jpg", alt:"Huckleberry café Santa Monica"},

  // ---------- SANTA MONICA · COWORKING ----------
  {k:"expertdojo", name:"Expert Dojo", area:"Santa Monica", type:"cowork", top:true,
   addr:"Santa Monica Place, Suite 308", cap:"<b>300</b> standing / <b>140</b> seated + rooftop",
   flag:"dedicated", link:"https://expertdojo.com/our-events/", linkText:"Events page", email:"sophie@expertdojo.com",
   note:"The proven Tech Week venue — 8,500 sq ft open floor plus a 14,669 sq ft ocean-view rooftop terrace. Has hosted LATW demo days and mixers.",
   img:null, alt:"Expert Dojo venue"},
  {k:"blankspaces_sm", name:"BLANKSPACES Santa Monica", area:"Santa Monica", type:"cowork",
   addr:"929 Colorado Ave, Santa Monica", lat:34.0192851, lng:-118.484814, cap:"~<b>200</b> · 3,800 sq ft event room + kitchen",
   flag:"dedicated", link:"https://www.blankspaces.com/event-space", linkText:"Event space", email:null,
   note:"The old Cross Campus flagship — the most Tech Week-storied room in SM. Enclosed event space with breakouts, own entrance, and an adjoining kitchen (ideal for coffee service). ☎ 323-330-9505",
   img:"https://images.squarespace-cdn.com/content/v1/6934b6171c384816b5c7df24/d54521d5-8c0a-4a39-864c-74001fb6375d/54734671496_c6b5c0efd7_k.jpg", alt:"BLANKSPACES Santa Monica interior"},
  {k:"wework", name:"WeWork 520 Broadway", area:"Santa Monica", type:"cowork",
   addr:"520 Broadway, Santa Monica", lat:34.0171, lng:-118.4943, cap:"<b>Flexible</b> · 40k sq ft over 2 floors",
   flag:"contact", link:"https://www.wework.com/buildings/520-broadway--los-angeles--CA", linkText:"Building page", email:null,
   note:"Building page advertises event spaces, offsites, and film-shoot rentals, indoor + outdoor — booked through the WeWork sales team.",
   img:"https://cdn-images.wework.com/images/E3C9F5DC-9028-11ED-9BE5-0ADB0235F9EB/e3c9f5dc-9028-11ed-9be5-0adb0235f9eb_0.jpg?width=800", alt:"WeWork 520 Broadway coworking floor"},
  {k:"industrious", name:"Industrious Santa Monica", area:"Santa Monica", type:"cowork",
   addr:"808 Wilshire Blvd, Suite 200", cap:"<b>&lt;50</b> · lounge-buyout territory",
   flag:"contact", link:"https://www.industriousoffice.com/locations/808-wilshire-boulevard-suite-200-santa-monica", linkText:"Location page", email:null,
   note:"Polished café/lounge that hosts community networking nights — but rooms are small, so it suits an intimate version of the event, not 200 people.",
   img:null, alt:"Industrious Santa Monica"},

  // ---------- VENICE · COFFEE ----------
  {k:"gjusta", name:"Gjusta", area:"Venice", type:"coffee", top:true,
   addr:"320 Sunset Ave, Venice", lat:33.9952744, lng:-118.4745783, cap:"Buyout <b>150</b> seated / <b>350</b> standing · courtyard 50/120",
   flag:"dedicated", link:"https://gjelinagroup.com/events/", linkText:"Events page", email:"events@gjelinagroup.com",
   note:"The iconic warehouse bakery — courtyard, private room, or full buyout through Gjelina Group's events team.",
   img:null, alt:"Gjusta bakery Venice"},
  {k:"penmar", name:"The Penmar", area:"Venice", type:"coffee", top:true,
   addr:"1233 Rose Ave, Venice", lat:34.0067158, lng:-118.4600616, cap:"<b>240</b> seated / up to <b>3,000</b> standing",
   flag:"dedicated", link:"https://thepenmar.com/events", linkText:"Events page", email:"events@thepenmar.com",
   note:"Gastro-clubhouse on Penmar Golf Course, coffee from 7am. Full day-event buyouts across indoor/outdoor zones, plus a 19-ft outdoor screen. Biggest capacity on this list.",
   img:"https://cdn.spotapps.co/spothopper/image/fetch/f_auto,q_auto:best,c_fit,h_1200/http://static.spotapps.co/spots/f1/144d3aa21c46c3af15a409f7332e4a/:original", alt:"The Penmar patio overlooking the golf course"},
  {k:"intelligentsia", name:"Intelligentsia Coffeebar", area:"Venice", type:"coffee",
   addr:"1331 Abbot Kinney Blvd, Venice", lat:33.9910884, lng:-118.4669225, cap:"~<b>50–80</b> · lofty room + patio",
   flag:"dedicated", link:"https://www.intelligentsia.com/pages/private-events", linkText:"Private events", email:null,
   note:"The marquee specialty-coffee name on Abbot Kinney, with a formal private-events/activations program including full-service café takeovers.",
   img:"https://cdn.shopify.com/s/files/1/0084/8802/6172/files/WS_Events_hero_img.png?v=1757624966", alt:"Intelligentsia events espresso bar"},
  {k:"greatwhite", name:"Great White", area:"Venice", type:"coffee",
   addr:"1604 Pacific Ave, Venice", cap:"~<b>75–150</b> · indoor + big patio",
   flag:"contact", link:"https://www.greatwhite.cafe/locations", linkText:"Locations + events", email:"events@greatwhite.cafe",
   note:"Big all-day café a block off the boardwalk, open 8am–10pm — one of the few Venice rooms that can hold a crowd from breakfast through happy hour.",
   img:"https://images.squarespace-cdn.com/content/v1/58a2162717bffc87643a0fc8/4fc7c9ef-a7f9-41a7-bacc-c66e87a490ee/great-white-restaurant-interior-architecture-sam-trude-design.webp", alt:"Great White Venice dining room"},
  {k:"butchersdaughter", name:"The Butcher's Daughter", area:"Venice", type:"coffee",
   addr:"1205 Abbot Kinney Blvd, Venice", lat:33.9916038, lng:-118.469208, cap:"Full buyout <b>100</b> seated / <b>200</b> cocktail",
   flag:"dedicated", link:"https://thebutchersdaughter.com/private-events", linkText:"Private events", email:"events@thebutchersdaughter.com",
   note:"Prime Abbot Kinney corner with a garden — sub-spaces are small, so it only works as a full buyout, booked via TripleSeat.",
   img:"https://images.squarespace-cdn.com/content/v1/653e71891dba722a34d415fe/7d0020df-6ac3-4ac6-ab07-3bcf7e52ffeb/BD_Venice_0079+copy.jpg", alt:"The Butcher's Daughter Venice dining space"},
  {k:"deus", name:"Deus Ex Machina", area:"Venice", type:"coffee",
   addr:"1001 Venice Blvd, Venice", lat:33.9943545, lng:-118.4528575, cap:"~<b>50–150</b> · courtyard + gallery",
   flag:"contact", link:"https://deuscustoms.com/pages/contact", linkText:"Contact", email:"hello@deuscustoms.com",
   note:"Café/moto-shop/gallery with a courtyard — the best vibe match for a tech crowd and a long event history. No formal events page; inquire by email or IG @deusemporium.",
   img:"https://deuscustoms.com/cdn/shop/articles/VENICE_CAFE.jpg?v=1699301538&width=5760", alt:"Deus Ex Machina Venice café building"},
  {k:"cowsend", name:"The Cow's End Café", area:"Venice", type:"coffee",
   addr:"34 Washington Blvd, Venice", lat:33.9794357, lng:-118.4657732, cap:"~<b>50–100</b> · two floors + private room",
   flag:"contact", link:"https://www.visitveniceca.com/2026/02/01/the-cows-end/", linkText:"Info page", email:null,
   note:"Two-story coffeehouse near the Venice Pier with an upstairs loft and a rentable private room. Book via Instagram @thecowsendcafe — no events page on their site.",
   img:"https://www.visitveniceca.com/wp-content/uploads/2026/02/Cows-End-1200x520.jpg", alt:"The Cow's End café"},

  // ---------- VENICE · COWORKING ----------
  {k:"blankspaces_venice", name:"BLANKSPACES Venice", area:"Venice", type:"cowork", top:true,
   addr:"606 Venice Blvd, Venice", cap:"Up to <b>200</b> · 4,000 sq ft hall + garden",
   flag:"dedicated", link:"https://www.blankspaces.com/eventspace-venice", linkText:"Event space", email:null,
   note:"Probably the strongest pure event-logistics option in Venice: 30-ft LED wall, pro AV, multi-camera recording, sliding doors to a garden, 85+ parking spots. Hosts Demo Day LA. ☎ 323-330-9505",
   img:"https://images.squarespace-cdn.com/content/v1/6934b6171c384816b5c7df24/1765062273965-P2LDETZ5A45HDWA4AOZ9/PXL_20241017_020313193.jpg", alt:"Reception inside BLANKSPACES Venice event space"},
  {k:"moss", name:"moss", area:"Venice", type:"cowork",
   addr:"1285 Electric Ave, Venice", cap:"~<b>50–150</b> · boutique clubhouse",
   flag:"dedicated", link:"https://www.mossvenice.com/private-events", linkText:"Private events", email:"team@mosscollective.co",
   note:"\"Coworking by day, event space by night\" — community kitchen, wellness rooms, and weekly founder programming. A perfect format match at boutique scale.",
   img:"https://cdn.prod.website-files.com/64f1c13f5c0dca2a22364d60/65ff40cc69736ba3dbaffc00_12%20homepage%20-%20our%20space%20organic%20interiors.webp", alt:"moss Venice organic interior"},
];
