// Page copy — CONFIG + TYPE_META + VENUES
const CONFIG = {
  kicker: "Nyc Tech Week · Venue Scout",
  title: "New York City — Venue Options",
  subtitle: "Event-capable cafes & event spaces in SoHo / Flatiron / Gowanus — for a Sept 25, 2026 bilingual tech-week coffee/hack event (~50–200 people). Links verified.",
  extraStat: {"n":"Sep 25","l":"NYC event date, 2026"},
  footnotes: [
    "<b>Neighborhood analysis:</b> SoHo/NoLita (Cursor Cafe takeover Oct 2025, Anthropic Claude Cafe Air Mail residency) is the cafe-takeover anchor; Flatiron/Union Sq (Civic Hall NY Tech Meetup, SOSA NYC) is the recurring-community spine; Gowanus/Downtown Brooklyn (ZeroSpace, Newlab) hosts the bigger-format hackathons.",
    "<b>Gone / don't route inquiries here:</b> 44 closure/discards logged.",
  ],
  provenance: "Researched Aug 2026 · EN · 27 → 24 shipped after contract (drops: Hotel 50 Bowery (JdV by Hyatt) – The Gallery & Crown, 6th Floor Loft (The Annex), Tarallucci e Vino NoMad) · Capacities published or estimated.",
};

const TYPE_META = {
  coffee: { label: "Coffee shop", icon: "☕" },
  cowork: { label: "Coworking / event space", icon: "🏢" },
};

const VENUES = [
  {
    "k": "citizens_of_soho",
    "name": "Citizens of SoHo",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "coffee",
    "addr": "201 Lafayette St, New York, NY 10012",
    "cap": "<b><b>60</b></b> seated / <b>120</b> standing",
    "flag": "dedicated",
    "link": "https://www.tagvenue.com/us/venues/new-york/61817/citizens-of-soho",
    "linkText": "Book via Tagvenue",
    "email": null,
    "note": "Australian-style all-day café directly on Lafayette in the heart of the target zone; whole-venue hire with in-house coffee/kitchen, so a bilingual hack day runs natively on their espresso bar. Listed on Tagvenue with published capacity and bookable form (their own domain is parked, so Tagvenue is the live booking surface).",
    "img": "https://www.tagvenue.com/resize/202511/4a/ff/widen-1680-noupsize;61817-citizens-of-soho-venue-pjRqwavT.jpg",
    "alt": "sunlit corner café interior with brick walls, neon sign, pendant lights and a long central bar at Citizens of SoHo",
    "top": true
  },
  {
    "k": "two_hands_noho",
    "name": "Two Hands NoHo",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "coffee",
    "addr": "74 Bleecker St, New York, NY 10012",
    "cap": "~<b><b>80</b></b> seated / ~<b>150</b> standing (est)",
    "flag": "dedicated",
    "link": "https://www.twohandshospitality.com/events",
    "linkText": "Two Hands private events page",
    "email": "noho@twohandshospitality.com",
    "note": "Australian café/restaurant with a dedicated private-events page and a published per-location events email (noho@). On the eastern edge of the target block (Bleecker at Lafayette/Bowery corner); room reads café-first with communal tables and an open bar, well-suited to a 100-person bilingual coffee-hack takeover.",
    "img": "https://images.getbento.com/accounts/3cca86fd1cad92b59651204131a0ae59/media/images/35137TwoHands_NoHo_Mar24_LAlmeida-4652.jpg?w=1200&fit=crop&auto=compress,format&cs=origin&crop=focalpoint&fp-x=0.5&fp-y=0.5",
    "alt": "bright corner café interior with white oak communal tables and an open coffee bar at Two Hands NoHo",
    "top": false
  },
  {
    "k": "think_coffee_soho",
    "name": "Think Coffee (SoHo)",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "coffee",
    "addr": "471 Broadway, New York, NY 10013",
    "cap": "~<b><b>60</b></b> seated across <b>2,000</b> sq ft (est)",
    "flag": "contact",
    "link": "https://thinkcoffee.com/pages/locations-catering",
    "linkText": "Think Coffee locations & catering page",
    "email": null,
    "note": "One of Think's largest rooms (2,000 sq ft, ~60 seats), directly on Broadway in the target corridor; events go through their office-catering line via ezCater rather than a dedicated events page, so a bilingual hack day becomes a structured after-hours buyout inquiry. Espresso-first room with plentiful outlets and a long window bar — classic Café Cursor shape.",
    "img": "https://thinkcoffee.com/cdn/shop/files/Rectangle_95_7_1.jpg?v=1773998272&width=1200",
    "alt": "airy Think Coffee SoHo interior with long window bar and booth seating under pendant lights",
    "top": false
  },
  {
    "k": "the_farm_soho",
    "name": "The Farm SoHo",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "coffee",
    "addr": "447 Broadway, 2nd Floor, New York, NY 10013",
    "cap": "<b><b>50</b></b> seated / <b>75</b> standing",
    "flag": "dedicated",
    "link": "https://www.thefarmsoho.com/event-venues/the-farm-soho",
    "linkText": "The Farm SoHo event venue page",
    "email": "hello@thefarmsoho.com",
    "note": "Hybrid cowork/event loft with a dedicated events page and published capacities on Broadway just below Canal; bottoms out the room-shape curve (50 max) but is the closest thing to a built-for-hack-day blank canvas with in-house coffee. Custom layouts, A/V, and booking flow at thefarmsoho.flexspace.ai are already live.",
    "img": "https://www.thefarmsoho.com/wp-content/uploads/2023/11/2-Loft-Venue-scaled.jpg",
    "alt": "exposed-brick loft event space at The Farm SoHo with wood floors and a long central worktable",
    "top": false
  },
  {
    "k": "218_nolita_event",
    "name": "218 Nolita Event Space",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "cowork",
    "addr": "218 Bowery, New York, NY 10012",
    "cap": "~<b><b>120</b></b> seated / ~<b>200</b> standing (est)",
    "flag": "contact",
    "link": "https://www.tagvenue.com/us/venues/new-york/54800/218-events",
    "linkText": "218 Events on Tagvenue",
    "email": null,
    "note": "Industrial-chic NoLita venue on Bowery with exposed brick, wooden floors, and a marble bar. The open-floor plan gives plenty of room for hack-day tables and mingling, and the 4,000 sq ft footprint can absorb a 50–200 person bilingual tech crowd.",
    "img": "https://www.tagvenue.com/resize/8f/88/fit-900-600;91673-218-event-space-room.jpg",
    "alt": "Exposed brick Nolita event loft with wooden floors and pendant lights",
    "top": false
  },
  {
    "k": "spring_place",
    "name": "Spring Place",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "cowork",
    "addr": "6 St Johns Lane, New York, NY 10013",
    "cap": "~<b><b>80</b></b> seated / ~<b>150</b> standing (est)",
    "flag": "contact",
    "link": "https://www.springplace.com",
    "linkText": "Spring Place NYC",
    "email": null,
    "note": "Members-only creative coworking and event hub in a converted Tribeca printing building. Multiple lounges, a restaurant/bar, and modular event spaces support a blended coffee-service + hacking format; on-site event team handles 50–200 person cultural and tech gatherings.",
    "img": "https://cdn.prod.website-files.com/68273a941eff82b585262fe9/68c9bf8cf8867fd3ccb540e8_Restaurant_1.webp",
    "alt": "Modern Spring Place lounge with contemporary furniture and warm lighting",
    "top": false
  },
  {
    "k": "neuehouse_madison_square",
    "name": "NeueHouse Madison Square",
    "area": "SoHo / NoLita (lower Manhattan, roughly Houston-Canal, Broadway-Lafayette)",
    "type": "cowork",
    "addr": "110 East 25th Street, New York, NY 10010",
    "cap": "<b><b>100</b></b> seated / <b>235</b> standing (Gallery); <b>240</b> (Penthouse)",
    "flag": "dedicated",
    "link": "https://www.neuehouse.com/private-events",
    "linkText": "NeueHouse Private Events",
    "email": null,
    "note": "Premium Flatiron creative workspace with terracotta-walled Gallery (projector, stepped seating) and a sunlit Penthouse. High-end coffee service and hospitality team are built for tech-adjacent gatherings; location is a short walk north of the strict SoHo/NoLita boundary.",
    "img": "https://images.ctfassets.net/rpinqlxtcitg/2bi4WkK97O0RdSblqGitCT/dc2a3b1c61f57288bd19fdc3d0a765d9/NH_-_Penthouse.jpg",
    "alt": "NeueHouse Madison Square Penthouse event space with city views",
    "top": false
  },
  {
    "k": "verci",
    "name": "Verci",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "coffee",
    "addr": "45 E 20th St, New York, NY 10003",
    "cap": "~<b><b>80</b></b> seated / <b>150</b> standing (est)",
    "flag": "dedicated",
    "link": "https://www.verci.com/events",
    "linkText": "Events at Verci",
    "email": "club@verci.com",
    "note": "3-story members' club with cafe/bar, social space, and rooftop (tour-trace seed via AI Tinkerers NY Tech Week Demo Day — hosted Builder of Things NY Tech Week 2026). Open floor plan and barista bar suit bilingual coffee/hack flow; can open to public bookings via 'Rent the space' link.",
    "img": "https://images.squarespace-cdn.com/content/v1/633267f31b2e7a42908c8155/68384256-1c82-4b4a-a3e3-639dffc7999a/2045+Clubhouse+-+Cafe%CC%81+%26+Bar.png",
    "alt": "Verci events space",
    "top": true
  },
  {
    "k": "moxy_chelsea_event",
    "name": "Moxy Chelsea Event Space + Lobby Cafe",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "coffee",
    "addr": "105 W 28th St, New York, NY 10001",
    "cap": "<b><b>150</b></b> standing / <b>120</b> seated; Lobby Bar full buyout <b>200</b> reception",
    "flag": "dedicated",
    "link": "https://www.moxychelsea.com/meetings-and-events",
    "linkText": "Meetings + Events",
    "email": "MoxyChelseaEvents@taogroup.com",
    "note": "Lobby cafe converts into day-to-night event space with terrace; meeting studios offer flexible hack-day layout. Hotel events team handles catering and AV; published capacities fit 50–200.",
    "img": "https://moxychelsea.com/content/uploads/sites/3/2025/06/tinywow_Feroce-Caffe_81898489-1-1920x1280.jpg",
    "alt": "Moxy Chelsea meeting and event space",
    "top": false
  },
  {
    "k": "resident_madison_park",
    "name": "Resident Madison Park / Union Square",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "coffee",
    "addr": "115 E 23rd St, New York, NY 10010",
    "cap": "~<b><b>50</b></b>–<b>120</b> (est, across spaces)",
    "flag": "contact",
    "link": "https://residentcompanyclub.com",
    "linkText": "Resident Company Club",
    "email": null,
    "note": "Curated startup coworking with event management support and lounge/cafe areas (tour-trace seed via AI Tinkerers Builder Co-working Day at Resident). Two nearby locations; contact directly for events availability.",
    "img": "https://ik.imagekit.io/7uki45mt9/images/tr:w-3840,f-webp,q-50/3f5fb63912ed68bd87020363704b806963a55cfa-2000x1333.jpg/19-DSC02313.webp",
    "alt": "Resident coworking lounge",
    "top": false
  },
  {
    "k": "blender_workspace",
    "name": "Blender Workspace",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "cowork",
    "addr": "135 Madison Ave, 8th Fl (at E 31st St), New York, NY 10016",
    "cap": "Auditorium: <b><b>250</b></b> theater / <b>300</b> standing · Event Suite: <b>100</b> theater / <b>200</b> standing (published)",
    "flag": "dedicated",
    "link": "https://blenderworkspace.com/event-space/",
    "linkText": "blenderworkspace.com/event-space",
    "email": null,
    "note": "Best all-around fit: 15,000 sq ft NoMad floor with a 5,000 sq ft auditorium and separate Event Suite sized exactly for a 50-200-person coffee/hack day, in-house hospitality bar, coffee, AV and catering, and a published client list (Google, Netflix, JPMorgan) that proves corporate tech events land here.",
    "img": "https://blenderworkspace.com/event-space/",
    "alt": "Blender Workspace 5000 sq ft window-lit auditorium on Madison Ave",
    "top": true
  },
  {
    "k": "betaworks",
    "name": "Betaworks",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "cowork",
    "addr": "29 Little W 12th St, New York, NY 10014 (just west of the cell, Meatpacking edge)",
    "cap": "<b><b>200</b></b> person street-level event space; 110 audience chairs; board room fits <b>25-40</b> (published)",
    "flag": "dedicated",
    "link": "https://www.betaworks.com/event-rentals",
    "linkText": "betaworks.com/event-rentals",
    "email": "eventsny@betaworks.com",
    "note": "Pre-vetted builder room: hosted AI Tinkerers OpenClaw Demo Night (Feb 2026) and the ClawHack NY 12-hour hackathon (Feb 28, 2026) — proven hack-day layout with stage, 160-inch projector, mics, bar, check-in lobby and back-of-house coffee prep. Tour-trace seed via AI Tinkerers NYC.",
    "img": "https://cdn.prod.website-files.com/6022fac80367ca7c9121c178/63ead9e92d440b265944d6c1_Betaworks_stage_hero.jpg",
    "alt": "Betaworks stage hero shot in the Meatpacking venue",
    "top": false
  },
  {
    "k": "nyc_seminar_conference",
    "name": "NYC Seminar & Conference Center",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "cowork",
    "addr": "114 W 26th St, 3rd Fl, New York, NY 10001",
    "cap": "Event Hall <b>2</b>: <b>200</b> seated / <b>250</b> standing (published); halls range 800-2,300 sq ft",
    "flag": "dedicated",
    "link": "https://nycseminarcenter.com/forms/",
    "linkText": "nycseminarcenter.com/forms",
    "email": "salesteam@nycseminarcenter.com",
    "note": "20-year Flatiron workhorse with combinable event halls up to ~2,300 sq ft, online Tripleseat booking, in-house catering and value pricing — a practical mid-budget room that comfortably swallows a 100-200-person day of hacking plus coffee service.",
    "img": "https://i0.wp.com/nycseminarcenter.com/wp-content/uploads/2024/04/NYCSCC_Misc-Room-Collage-Medium.jpg?resize=768%2C768&ssl=1",
    "alt": "NYC Seminar & Conference Center event rooms",
    "top": false
  },
  {
    "k": "the_malin_flatiron",
    "name": "The Malin Flatiron",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "cowork",
    "addr": "895 Broadway, 5th Fl, New York, NY 10003",
    "cap": "<b>32,700</b>sq ft floor; meeting rooms up to <b>30</b> ppl; private events from intimate to full buyout ~<b>60-120</b> (est)",
    "flag": "contact",
    "link": "https://themalin.co/locations/flatiron/",
    "linkText": "themalin.co/locations/flatiron",
    "email": null,
    "note": "Design-forward coworking floor one block off Union Square whose private-events section offers hires from offsites to full buyouts; AI/VC-heavy member base is the exact crowd for a tech-week coffee day. Bookable-capacity details only via inquiry, hence contact flag.",
    "img": "https://themalin.co/locations/flatiron/",
    "alt": "The Malin Flatiron lounge",
    "top": false
  },
  {
    "k": "union_square_loft",
    "name": "Union Square Loft",
    "area": "Flatiron / Union Square / Chelsea (roughly 14th-30th St, 5th-7th Ave)",
    "type": "cowork",
    "addr": "873 Broadway, Suite 408, New York, NY 10003 (Flatiron)",
    "cap": "<b><b>60</b></b> total: 45 theater / 35 seated / 55 standing (published)",
    "flag": "dedicated",
    "link": "https://unionsquareloft.com",
    "linkText": "unionsquareloft.com",
    "email": null,
    "note": "Intimate all-inclusive Flatiron loft with 13-ft ceilings, pro Fulcrum sound and everything included (furniture, lighting, AV) — a plug-and-play room for the 50-60-person end of the range; partners with neighboring spaces for larger builds.",
    "img": "https://unionsquareloft.com/wp-content/uploads/2026/03/Open-loft.jpg",
    "alt": "Union Square Loft open-floor hero",
    "top": false
  },
  {
    "k": "public_records_cafe",
    "name": "Public Records (Cafe Public)",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "coffee",
    "addr": "233 Butler St, Brooklyn, NY 11217",
    "cap": "<b><b>200</b></b> standing / <b>200</b> seated across rooms (published by EventUp venue listing); five linked rooms let a 50–200 hack-day scale up/down",
    "flag": "dedicated",
    "link": "https://publicrecords.nyc",
    "linkText": "PUBLIC RECORDS — private events link on homepage",
    "email": "parties@publicrecords.nyc",
    "note": "In-zone at 233 Butler, ~never more than a 2-min walk from 337 Butler. The historic ASPCA HQ holds a record bar + all-day vegan Cafe Public + Sound Room + Atrium + plant-nursery courtyard (The Nursery) — daytime cafe over Sitting-capacity performance rooms, exactly the coffee+builder shape; full-time events inbox parties@publicrecords.nyc and a dedicated 'PRIVATE EVENTS' form linked from the homepage. Room-shape fit: Cafe Public is the coffee front-room, Sound Room/Nursery absorb 50–200 builders with house sound and backing kitchen.",
    "img": "https://publicrecords.nyc/wp-content/uploads/2025/11/atrium-cheers-3-copy-450x300.jpg",
    "alt": "Public Records Atrium interior with guests seated around the bar under exposed steel beams",
    "top": true
  },
  {
    "k": "devocin_downtown_brooklyn",
    "name": "Devoción — Downtown Brooklyn",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "coffee",
    "addr": "276 Livingston St, Brooklyn, NY 11201 (corner of Bond)",
    "cap": "~<b><b>80</b></b> seated / ~<b>120</b> standing (est) — 1,700+ sq ft hall with 18-ft floor-to-ceiling windows and indoor tropical garden, Boerum Hill × Downtown BK edge",
    "flag": "contact",
    "link": "https://www.devocion.com/pages/devocion-cafe-downtown-brooklyn-ny",
    "linkText": "Devoción — Downtown Brooklyn page",
    "email": null,
    "note": "Devoción's largest Downtown-Brooklyn room sits right at the Boerum Hill edge of the cell, ~never a 10-min walk from 337 Butler. A high-ceiling, plant-filled cafe that routinely runs community pop-ups — the direct-trade farm-fresh Colombian coffee program is also a bilingual hook (EN/ES on menus and bags). No published events inbox on this page; flag as contact via the cafe's main line listed on-site.",
    "img": "https://www.devocion.com/cdn/shop/files/DowntownBK_Devocion_LizClayman_001_1.jpg",
    "alt": "Devoción Downtown Brooklyn cafe interior with tropical indoor garden and 18-foot windows",
    "top": false
  },
  {
    "k": "brooklyn_roasting_company",
    "name": "Brooklyn Roasting Company — Navy Yard Roastery HQ",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "coffee",
    "addr": "Building 123, Brooklyn Navy Yard, Brooklyn, NY 11205",
    "cap": "~<b><b>150</b></b> standing (est) — 120-year-old industrial roastery with 60-ft ceilings, private-event buyouts offered by the roastery",
    "flag": "contact",
    "link": "https://www.brooklynroasting.com/pages/about-us-2",
    "linkText": "Brooklyn Roasting — About / private events",
    "email": "info@brooklynroasting.com",
    "note": "Working roastery inside the Navy Yard (adjacent to Newlab) that explicitly opens its shipyard-scale floor for fully-customizable private events ('no idea is too big'). On-site coffee program is the venue's own roast — a self-catering hack-day room. Reachable events contact published as info@brooklynroasting.com on the linked contact page.",
    "img": "https://www.brooklynroasting.com/cdn/shop/files/OneClintonDSCF0911.jpg",
    "alt": "Latte art in a Brooklyn Roasting Company mug at the Navy Yard roastery cafe",
    "top": false
  },
  {
    "k": "brooklyn_roasting_company_200flu",
    "name": "Brooklyn Roasting Company — 200 Flushing Ave Outpost",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "coffee",
    "addr": "200 Flushing Ave, Brooklyn, NY 11205 (Navy Yard edge, by Newlab)",
    "cap": "~<b><b>40</b></b> seated (est) — satellite outpost cafe open 6am–7pm daily, walkable to Newlab",
    "flag": "contact",
    "link": "https://www.brooklynroasting.com/blogs/cafe/our-new-outpost-at-200-flushing-avenue-is-now-open",
    "linkText": "BRC blog — 200 Flushing outpost open",
    "email": "info@brooklynroasting.com",
    "note": "BRC's newest full-service outpost sits at the Navy Yard edge right by Newlab, open 6am–7pm daily — best as an overflow/day-two brew base for smaller workshop pods (est. 40 seats) while the roastery hosts the main room. Same published contact as HQ: info@brooklynroasting.com / (718) 855-1000.",
    "img": "https://www.brooklynroasting.com/cdn/shop/articles/photo_90733193-9078-4e49-a541-79b7b1275afb.jpg?v=1692852057&width=1066",
    "alt": "Brooklyn Roasting Company 200 Flushing Ave outpost",
    "top": false
  },
  {
    "k": "the_shop_at",
    "name": "The Shop at 420 Carroll",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "cowork",
    "addr": "420 Carroll St, 2nd Floor, Brooklyn, NY 11215",
    "cap": "~<b><b>150</b></b>–<b>200</b> event / <b>12,000</b> sq ft total (est)",
    "flag": "dedicated",
    "link": "https://shopworkspace.com/membership/meeting-space-events/",
    "linkText": "Meeting & Event Space",
    "email": "infobk@shopworkspace.com",
    "note": "New 12,000-sq-ft Gowanus coworking space with outdoor patio deck, breakout rooms, hospitality support and FlexSpace booking; walking distance to Union St R station, Beanmonger coffee on site.",
    "img": "https://shopworkspace.com/wp-content/uploads/2026/05/Screenshot-2026-05-18-152000_1240x880_acf_cropped.png",
    "alt": "Outdoor patio deck at The Shop Brooklyn, Gowanus Canal",
    "top": true
  },
  {
    "k": "newlab",
    "name": "Newlab",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "cowork",
    "addr": "19 Morris Ave, Building 128, Brooklyn Navy Yard, Brooklyn, NY 11205",
    "cap": "<b><b>250</b></b> seated / <b>250</b> standing in main Event Space (plus Mezzanine 250 + Bridge 90)",
    "flag": "dedicated",
    "link": "https://www.newlab.com/locations/brooklyn",
    "linkText": "Newlab Brooklyn location",
    "email": null,
    "note": "Tour-trace seed via CreativeMornings (hosted NYC's May 2026 Release Day). 84,000 sq ft inside the Navy Yard with a dedicated 250-cap event space, on-site café, and a critical-tech builder community already in residence; note their contact page says no free event-space requests — inquiries via contact form.",
    "img": "https://cdn.prod.website-files.com/677376e1e97650585235ab96/6836d463bbc693d27f6614f0_NewlabBrooklyn_04.avif",
    "alt": "Newlab industrial loft event hall, Building 128 Brooklyn Navy Yard",
    "top": false
  },
  {
    "k": "zerospace",
    "name": "ZeroSpace",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "cowork",
    "addr": "337-345 Butler St, Brooklyn, NY 11217",
    "cap": "~<b><b>300</b></b>+ across <b>40,000</b> sq ft of rentable warehouse (est; Studio B alone 16,500 sq ft)",
    "flag": "dedicated",
    "link": "https://www.zerospace.co/studios/venue",
    "linkText": "The Space — venue rental page",
    "email": null,
    "note": "Sits literally at the target address (337-345 Butler St). Four interconnected mostly column-free studios with 16–35 ft ceilings, drive-in loading bays, plus a Luma-hosted community events calendar for tech/arts meetups.",
    "img": "https://images.squarespace-cdn.com/content/v1/61c4a90f724d79385b3a744d/1640722734890-YBHYZAK147LAEF64IDL2/DSC09381.jpg",
    "alt": "ZeroSpace Studio B, 16,500 sq ft daylight warehouse",
    "top": false
  },
  {
    "k": "littlefield",
    "name": "littlefield",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "cowork",
    "addr": "635 Sackett St, Brooklyn, NY 11217",
    "cap": "<b><b>300</b></b> in Performance Space / <b>150</b> full-venue private rental",
    "flag": "contact",
    "link": "https://littlefieldnyc.com",
    "linkText": "littlefield home",
    "email": "booking@littlefieldnyc.com",
    "note": "Converted 6,200 sq ft Gowanus warehouse with stage, EAW A/V, gallery/bar front room; 300-capacity performance room or movable-partition 100-cap gallery + bar. Day-time coffee-hack friendly industrial shape in the heart of the target zone.",
    "img": "https://littlefieldnyc.com/wp-content/uploads/2021/02/Exterior_mural-scaled.jpg",
    "alt": "littlefield exterior mural wall",
    "top": false
  },
  {
    "k": "civic_hall_nyc",
    "name": "Civic Hall NYC (The Bernard Goldstein Center)",
    "area": "Gowanus / Boerum Hill / Downtown Brooklyn edge (around 337 Butler St, plus adjacent Navy Yard / Newlab)",
    "type": "cowork",
    "addr": "124 East 14th St, New York, NY 10003",
    "cap": "<b><b>250</b></b> gala / <b>300</b>+ keynote / <b>500</b>+ standing in Craig Newmark Auditorium; 10–800 overall",
    "flag": "dedicated",
    "link": "https://www.civichall.org/nyceventvenue",
    "linkText": "NYC Event Venue — Civic Hall",
    "email": null,
    "note": "Tour-trace seed via NYC AI Tinkerers (hosted the ElevenLabs Worldwide Hackathon Dec 2025 and several 2026 chapter events). Union Square transit hub, nonprofit rates, proven 100–150-person hackathon room; a short F/L/N/R/W hop from Downtown Brooklyn.",
    "img": "https://cdn.prod.website-files.com/65c43c2479e30f10b200c063/65d2e688c520c9a4b7ddd009_20231115_151913%201.png",
    "alt": "Craig Newmark Auditorium wall of glass facing Irving Place",
    "top": false
  }
];
