// Page copy — GENERATED by assemble_city_config.py, 2026-08-06
const CONFIG = {
  kicker: "New York · ComputeCafe",
  title: "New York — Venue Options",
  subtitle: "Event-capable cafes, coworking & event spaces in Flatiron / Union Square and Williamsburg / Dumbo — for the Sep 25, 2026 tech coffee/hack event (~50–200 people). Links point to verified private-events pages or booking contacts.",
  extraStat: { n: "Sep 25", l: "New York event date, 2026" },
  footnotes: [
    "<b>Neighborhood analysis:</b> Flatiron / Union Square is Manhattan's most transit-central tech cluster (Zero Irving's purpose-built tech hub, Silicon Alley legacy); Williamsburg / Dumbo carries Brooklyn's builder-café scene — Cafe Cursor's NYC takeover is a Brooklyn café, though tour hosts (Ideal Glass, Betaworks, ElevenLabs office) mostly sit outside these two cells or behind registration gates.",
    "<b>Gone / don't route inquiries here:</b> Brooklyn Roasting Company — 25 Jay St, DUMBO flagship: closed — no longer listed on brooklynroasting.com/pages/our-stores (fetched Aug 6 2026); brand now lists only 200 Flushing Ave, 1 Clinton St, and 543 Metropolitan Ave.",
    "<b>Confirmed host:</b> the Sep 25 event runs at First Round's on Me — Cafe Social Club (109 W 25th St, Chelsea). The rest of the lineup is the vetted overflow / satellite list.",
    "<b>RSVP:</b> the New York event page is live — <a href=\"https://luma.com/tavily-nnzl\" target=\"_blank\" rel=\"noopener\">register on Luma ↗</a>.",
  ],
  provenance: "Researched & links verified Aug 6–7, 2026 · Photos load from each venue's own website; placeholder art covers the rest. Capacities are published or estimated — confirm when booking.",
};

const TYPE_META = {
  coffee: { label: "Coffee shop", icon: "☕" },
  cowork: { label: "Coworking / event space", icon: "🏢" },
};

// Discarded during research (scope/fit — NOT closures; for the review card, not the page):
//   dropped: ClawCon NYC tour-trace seed — host venue was Ideal Glass Studios (Manhattan event studio, 1,313 RSVPs), not a café; outside the coffee cell.
//   dropped: Cafe Cursor NYC (Aug 12 2026) tour-trace seed — Brooklyn host café never publicly named (Luma address gated behind registration, GarysGuide lists 'Venue To Be Announced', forum thread silent); no venue to verify. Prior SoHo edition equally gated.
//   dropped: AI Tinkerers NYC tour-trace seed — past 'coworking cafe' sessions were hosted at sponsor offices (Betaworks, MongoDB/Javits Center), not standalone cafés; nyc.aitinkerers.org also returned 403 on direct fetch.
//   dropped: Sey Coffee — operating at 18 Grattan St, Brooklyn 11206 (East Williamsburg/Bushwick edge per seycoffee.com), outside the core Williamsburg/Dumbo cell; closes 5pm weekdays with no events program listed.
//   dropped: Devoción DUMBO (105 York St) — open per devocion.com/pages/cafes but redundant with the larger Williamsburg flagship one neighborhood over; kept Usagi as the DUMBO pick instead.
//   dropped: Ideal Glass Studios — ClawCon NYC host (Mar 4, 2026 per search results incl. trymimetic.com) but located in West Village, outside both target neighborhoods
//   dropped: Betaworks — ClawHack NY host (betaworks.com/event/clawhack-ny) but in Meatpacking District, outside both target neighborhoods
//   dropped: ElevenLabs NYC office — hosted the AI Tinkerers ElevenLabs Worldwide Hackathon (100+ participants per elevenlabs.io blog) but it is a sponsor's private office, not publicly bookable; partner lead only
//   dropped: Pilot (Dabl Club NYC Founders & Investors Winter Social host, luma.com/sryjeq4l) — physical venue intentionally undisclosed on public page ('shared with attendees day before event'), 28-person social; partner lead, not a verifiable bookable venue
//   dropped: Bond Collective Vinegar Hill (295 Front St, Brooklyn) — largest bookable room seats 10 and location is waitlisted for new members; cannot host a 50-200 person event
//   dropped: The Malin (Williamsburg candidate) — themalin.com unreachable on two attempts (connection refused); current offering could not be verified this session

const VENUES = [
  {
    "k": "firstroundsonme",
    "name": "First Round's on Me — Cafe Social Club",
    "area": "Flatiron / Union Square",
    "type": "coffee",
    "addr": "109 W 25th St (Chelsea), New York, NY 10001",
    "cap": "not published — café + social floor; ~<b>60</b>–<b>100</b> (est), confirm with the team",
    "flag": "contact",
    "link": "https://linktr.ee/firstroundsonmeapp",
    "linkText": "linktr.ee/firstroundsonmeapp (own site unreachable at research time)",
    "email": null,
    "note": "✔ CONFIRMED HOST of the Sep 25 NYC event. Cafe/podcast/social club from the FROM dating-app team (opened May 2025): coffee bar, DJ + podcast setup, pool-table social floor — built for exactly this crowd. Daily 8am–4pm; evening events by arrangement.",
    "img": null,
    "alt": "Neon-lit social floor at Cafe Social Club",
    "top": true
  },
  {
    "k": "devocinwilliamsburgflagship",
    "name": "Devoción — Williamsburg Flagship",
    "area": "Williamsburg / Dumbo",
    "type": "coffee",
    "addr": "148 Grand St, Brooklyn, NY 11249",
    "cap": "~<b>80</b> seated / <b>150</b> standing (est)",
    "flag": "contact",
    "link": "https://www.devocion.com/pages/new-york-coffee-shop-williamsburg-brooklyn",
    "linkText": "devocion.com — Williamsburg café",
    "email": null,
    "note": "Greenhouse-style flagship with skylight, lush plantings, dual espresso bars and an on-site training lab already used for public classes and cuppings — the strongest coffee/hack-day room in Brooklyn. Open 7am-6pm daily.",
    "img": "https://www.devocion.com/cdn/shop/files/Devocion_Wburg_1025_LizClayman_012_3.jpg",
    "alt": "Sunlit greenhouse-style café interior with skylight and tropical plants",
    "top": true
  },
  {
    "k": "usaginy",
    "name": "Usagi NY",
    "area": "Williamsburg / Dumbo",
    "type": "coffee",
    "addr": "163 Plymouth St, Brooklyn, NY 11201",
    "cap": "~<b>60</b> seated / <b>100</b> standing (est, ~2,800-3,000 sq ft)",
    "flag": "contact",
    "link": "https://www.usaginy.com/",
    "linkText": "usaginy.com",
    "email": "connect@usaginy.com",
    "note": "Sou Fujimoto-designed café/gallery/library hybrid in DUMBO with 15 removable track-mounted panels for reconfiguring the room — purpose-built for takeovers, talks and workshops. Direct events email listed.",
    "img": null,
    "alt": "Minimalist white café-gallery interior with movable panels",
    "top": false
  },
  {
    "k": "brooklynroastingcompanymetropolitanave",
    "name": "Brooklyn Roasting Company — Metropolitan Ave",
    "area": "Williamsburg / Dumbo",
    "type": "coffee",
    "addr": "543 Metropolitan Ave, Brooklyn, NY 11211",
    "cap": "~<b>40</b> seated / <b>60</b> standing (est)",
    "flag": "contact",
    "link": "https://www.brooklynroasting.com/pages/our-stores",
    "linkText": "brooklynroasting.com — our cafés",
    "email": null,
    "note": "The roaster's surviving Williamsburg café — open 7am-7pm daily with private tours/tastings offered, so staff are used to groups. Best as an overflow or satellite room; too small to solo-host 200. Phone (347) 799-1173.",
    "img": null,
    "alt": "Industrial roastery café with coffee sacks and brew bar",
    "top": false
  },
  {
    "k": "devocinflatiron",
    "name": "Devoción — Flatiron",
    "area": "Flatiron / Union Square",
    "type": "coffee",
    "addr": "25 E 20th St, New York, NY 10003",
    "cap": "~<b>60</b> seated / <b>100</b> standing (est)",
    "flag": "contact",
    "link": "https://www.devocion.com/pages/cafes",
    "linkText": "devocion.com — café locations",
    "email": null,
    "note": "Devoción's large Flatiron room two blocks from Union Square carries the same plant-filled, high-design DNA as the Brooklyn flagship, and one brand relationship could cover both boroughs of the tour. Open 7am-6pm.",
    "img": null,
    "alt": "Plant-lined café interior with leather seating and espresso bar",
    "top": false
  },
  {
    "k": "thinkcoffeeunionsquare",
    "name": "Think Coffee — Union Square",
    "area": "Flatiron / Union Square",
    "type": "coffee",
    "addr": "123 4th Ave, New York, NY 10003",
    "cap": "~<b>50</b> seated / <b>80</b> standing (est)",
    "flag": "contact",
    "link": "https://www.thinkcoffee.com/pages/locations-catering",
    "linkText": "thinkcoffee.com — locations & catering",
    "email": null,
    "note": "Spacious, laptop-friendly room just off Union Square, open 7am-7pm with every subway line nearby; chain also runs a Flatiron shop at 568 6th Ave and does catering via EZCater. Book by phone (646) 991-0342.",
    "img": null,
    "alt": "Open-plan coffee shop with communal work tables",
    "top": false
  },
  {
    "k": "irvingfarmnewyorkgramercy71irvingplace",
    "name": "Irving Farm New York — Gramercy (71 Irving Place)",
    "area": "Flatiron / Union Square",
    "type": "coffee",
    "addr": "71 Irving Pl, New York, NY 10003",
    "cap": "~<b>40</b> seated / <b>60</b> standing (est)",
    "flag": "contact",
    "link": "https://irvingfarmcoffee.com/pages/locations",
    "linkText": "irvingfarmcoffee.com — locations",
    "email": null,
    "note": "The original Irving Farm café a block from Union Square — confirmed operating on the current locations page. Cozy neighborhood energy for a smaller-format hack morning rather than the full 200-person day.",
    "img": null,
    "alt": "Classic brick-walled café on a tree-lined Gramercy corner",
    "top": false
  },
  {
    "k": "zeroirving",
    "name": "Zero Irving",
    "area": "Flatiron / Union Square",
    "type": "cowork",
    "addr": "124 E 14th St, New York, NY 10003",
    "cap": "<b>~200</b> (est) — 14,000 sq ft event & conference center on the 2nd floor",
    "flag": "contact",
    "link": "https://zeroirving.com/",
    "linkText": "zeroirving.com",
    "email": null,
    "note": "Purpose-built Union Square tech hub (opened 2023): flexible office/coworking floors, a tech training center, and a dedicated double-height conference/event venue — the strongest hack-day shape in the cell. Event page not linked from homepage; inquire via zeroirving.com/contact.",
    "img": "https://zeroirving.com/wp-content/themes/zeroirving/_content/building/home_lobby_rendering_intro.jpg",
    "alt": "Double-height lobby at 124 E 14th St",
    "top": true
  },
  {
    "k": "theyardflatironsouth",
    "name": "The Yard: Flatiron South",
    "area": "Flatiron / Union Square",
    "type": "cowork",
    "addr": "234 Fifth Ave (at 27th St), New York, NY",
    "cap": "<b>~75-125</b> (est) across lounges and conference rooms",
    "flag": "contact",
    "link": "https://theyard.com/flatiron-south-coworking/",
    "linkText": "theyard.com/flatiron-south-coworking",
    "email": null,
    "note": "Coworking floors with exposed brick, Fifth Ave views, art-lined lounges, and a private conference room per floor; meeting/space rental via FlexSpace, larger buyouts by inquiry. No published event capacity — confirm headcount for 50+.",
    "img": "https://theyard.com/wp-content/uploads/2025/02/copy-of-006-min-1024x683.jpg",
    "alt": "Art-lined coworking lounge over Fifth Avenue",
    "top": false
  },
  {
    "k": "newlab",
    "name": "Newlab",
    "area": "Williamsburg / Dumbo",
    "type": "cowork",
    "addr": "19 Morris Ave, Brooklyn Navy Yard (between Dumbo and Williamsburg), Brooklyn, NY",
    "cap": "<b>~100-300</b> (est) — 84,000 sq ft facility",
    "flag": "dedicated",
    "link": "https://newlab.com/host-an-event",
    "linkText": "newlab.com/host-an-event",
    "email": null,
    "note": "Deep-tech innovation hub in the Navy Yard with a long history of hosting hackathons and demo days; dedicated event-rental intake via TripleSeat (newlab.tripleseat.com). Note: paid rentals only — they state no free event space or tours currently.",
    "img": null,
    "alt": "Vaulted machine-shop hall turned innovation hub",
    "top": true
  },
  {
    "k": "theyardwilliamsburg",
    "name": "The Yard: Williamsburg",
    "area": "Williamsburg / Dumbo",
    "type": "cowork",
    "addr": "195 Broadway, Brooklyn, NY 11211",
    "cap": "<b>~75-100</b> (est)",
    "flag": "contact",
    "link": "https://theyard.com/williamsburg-coworking/",
    "linkText": "theyard.com/williamsburg-coworking",
    "email": null,
    "note": "South Williamsburg coworking with 24/7 access, conference rooms, spacious lounges and a monthly events program; meeting rooms bookable via FlexSpace, staffed M-F with an on-site community manager ((646) 233-2786). Buyout capacity for 50+ needs confirmation.",
    "img": "https://theyard.com/wp-content/uploads/2023/12/12132023_pf_the_yard_williamsburg_19-1024x683.jpg",
    "alt": "Sunlit coworking lounge at 195 Broadway",
    "top": false
  },
  {
    "k": "greendeskdumbo",
    "name": "Green Desk (Dumbo)",
    "area": "Williamsburg / Dumbo",
    "type": "cowork",
    "addr": "68 Jay St & 195 Plymouth St, Dumbo, Brooklyn, NY (also 240 Kent Ave, Williamsburg)",
    "cap": "<b>~50-100</b> (est) in their large event spaces",
    "flag": "contact",
    "link": "https://greendesk.com/",
    "linkText": "greendesk.com",
    "email": "sales@greendesk.com",
    "note": "Dumbo-born flexible coworking operator with multiple buildings in the neighborhood; advertises 'conference and events in one of our fantastic large event spaces,' pricing varies by location. Good budget-friendly hack-day base steps from the waterfront.",
    "img": null,
    "alt": "Loft-style Dumbo coworking floor",
    "top": false
  },
  {
    "k": "dumboloft",
    "name": "Dumbo Loft",
    "area": "Williamsburg / Dumbo",
    "type": "cowork",
    "addr": "155 Water St, Brooklyn, NY 11201",
    "cap": "<b>140</b> seated / <b>200</b> standing (per venue listings; 3,200+ sq ft)",
    "flag": "dedicated",
    "link": "https://thedumboloft.com/",
    "linkText": "thedumboloft.com",
    "email": "info@bkvenues.com",
    "note": "1891 loft with high ceilings, wood columns, exposed brick and Manhattan Bridge views; a flexible raw rental space (run by BK Venues) that comfortably fits a 50-200 person coffee/hack day — bring your own AV/furniture plan. Same building also houses Green Desk coworking.",
    "img": "https://www.thedumboloft.com/wp-content/uploads/2019/04/DUMBO-Loft-Events_3.jpg",
    "alt": "Exposed-brick loft with wood columns",
    "top": false
  }
];
