// Page copy — CONFIG + TYPE_META + VENUES
const CONFIG = {
  kicker: "Seoul · ComputeCafe",
  title: "Seoul — Venue Options",
  subtitle: "Event-capable cafes & event halls in Gangnam / Seongsu / Sinchon-Hongdae — for a Sept 11, 2026 bilingual (KR/EN) tech-week coffee/hack event (~50–200 people). Links verified (Korean scripts preserved).",
  extraStat: {"n":"Sep 11","l":"Seoul event date, 2026"},
  footnotes: [
    "<b>Neighborhood analysis:</b> Gangnam-Teheran-ro (Hashed Lounge, Maru180, AMD Aloft) is where AI Tinkerers Seoul + Cursor Meetups actually ran; Seongsu-dong warehouse conversions (Elice Lab, Seoul Startup Hub Seongsu) are Seoul's hackable cafe-district; Sinchon/Hongdae (Yonsei, SKYST consortium) anchors the bilingual student/indie-builder crowd.",
    "<b>Gone / don't route inquiries here:</b> Google for Startups Campus Seoul (캠퍼스 서울, formerly at Yeoksam-ro 165 Autoway Tower) — permanently closed in 2020, removed from consideration [UNVERIFIED — needs a fetched source before this claim is relied on]",
    "<b>Booking note:</b> Many booking paths are via ShareIt (shareit.kr) or SpaceCloud (spacecloud.kr) — KakaoTalk channels surface when venues list them.",
  ],
  provenance: "Researched Aug 2026 · Bilingual KR/EN · 27 → 27 shipped after contract (drops: none) · Capacities published or estimated.",
};

const TYPE_META = {
  coffee: { label: "Coffee shop", icon: "☕" },
  cowork: { label: "Coworking / event space", icon: "🏢" },
};

const VENUES = [
  {
    "k": "booksays",
    "name": "BOOKSAYS 북쌔즈",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "coffee",
    "addr": "서울특별시 강남구 테헤란로 311 아남타워 정면 2층 (후면길 1층) / 311 Teheran-ro, Anam Tower 2F, Yeoksam-dong, Gangnam-gu, Seoul 06151",
    "cap": "<b>100</b>(메인홀 Main Hall; lounges: 20인 우주선 / 10인 잠수함)",
    "flag": "dedicated",
    "link": "https://booksays.co.kr/reservation",
    "linkText": "북쌔즈 공간예약 페이지 (Main Hall/라운지 대관료 및 신청)",
    "email": "booksays@naver.com",
    "note": "1층 책방+베이커리 카페와 2층 100명 메인홀이 붙어 있는 복합문화공간이라, 커피 브레이크+해커톤+키노트를 한 건물에서 이어가기 좋다. 빔프로젝터·대형스크린·피아노·음향장비가 대관료에 포함이고 오전/저녁 타임이 따로 책정돼 있어 반일형 이벤트에 유리.",
    "img": "https://cdn.imweb.me/thumbnail/20220905/534d3f061bc5c.jpg",
    "alt": "북쌔즈 메인홀 - 토속 서가와 무대가 결합된 100석 규모 강연장",
    "top": true
  },
  {
    "k": "ground_b",
    "name": "GROUND B 그라운드비 카페",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "coffee",
    "addr": "서울특별시 강남구 테헤란로92길 7 바른빌딩 1층 / 1F, 7 Teheran-ro 92-gil, Daechi-dong, Gangnam-gu, Seoul",
    "cap": "<b>100</b>seated, 120 standing (테라스·실외 포함) — published by ShareIt host",
    "flag": "dedicated",
    "link": "https://shareit.kr/store/7670",
    "linkText": "그라운드비 카페 - 쉐어잇 대관 페이지 (공간 스펙·빔+마이크·대관시간 안내)",
    "email": null,
    "note": "삼성역 1분·층고 5m·80평 규모+테라스가 있는 순수 카페. 200인치 빔+무선마이크 2대 구비, 평일 16시 이후·주말 시간 협의(취소 최소 5H)로 저녁 해커톤/밋업과 주말 하프데이 모두 가능. 대관은 쉐어잇(Share.it)과 스페이스클라우드(공간ID 58414) 채널을 통해 신청하며, 카카오톡/전화 직통 이메일은 공개되어 있지 않다.",
    "img": null,
    "alt": "그라운드비 카페 내부 - 층고 5m 통창과 초록 식물, 테라스가 있는 대형 공간",
    "top": false
  },
  {
    "k": "mode_lounge_yeoksam",
    "name": "모드라운지 역삼점 Mode Lounge Yeoksam",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "coffee",
    "addr": "서울특별시 강남구 테헤란로22길 11 모닝타워 지하 1층 / B1, 11 Teheran-ro 22-gil, Yeoksam-dong, Gangnam-gu, Seoul",
    "cap": "기준 <b>10</b>명, 최대 80명 (직사각형 배치 시 108명) — published",
    "flag": "dedicated",
    "link": "https://www.weebur.com/products/TSAE3M72ZK",
    "linkText": "[역삼역] 모드라운지 역삼점 - 위버 대관 페이지 (커피 브레이크·케이터링 옵션 포함)",
    "email": "weebur@weebur.com",
    "note": "역삼역 3번출구 도보 2분, 인더스트리얼 라운지 무드의 독채형 대관홀. 커피 브레이크·케이터링을 인하우스 패키지처럼 주문할 수 있어 50-100명 기술 워크숍/해커데이에 적합. 2022년 오픈, 프로젝터·150인치 스크린·4채널 스피커+무선마이크 2대 기본 제공.",
    "img": "https://cdn.weebur.com/images/DAYVKZ91A8ZGL3AAGUXR.jpg",
    "alt": "모드라운지 역삼점 홀 - 바 스타일 카운터와 라운지 테이블이 섞인 모던 인더스트리얼 인테리어",
    "top": false
  },
  {
    "k": "mmc",
    "name": "MMC 카페 마일드 모디쉬 클럽",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "coffee",
    "addr": "서울특별시 강남구 언주로69길 6 제남빌딩 1층 101호 / 101, 1F Jenam Bldg, 6 Onju-ro 69-gil, Yeoksam-dong, Gangnam-gu, Seoul",
    "cap": "<b>~30</b>명 (카페 약 25평 규모, est)",
    "flag": "dedicated",
    "link": "https://www.spacecloud.kr/space/62883",
    "linkText": "역삼 mmc카페[모임 및 행사O] - 스페이스클라우드 대관 페이지",
    "email": null,
    "note": "역삼역과 선릉역 사이 언주로 골목의 아늑한 디저트·스페셜티 카페. 마이크/음악재생/와이파이 이용 가능하고 30명 규모 소규모 워크숍이나 사이드 이벤트에 적합. 대관은 스페이스클라우드 채널톡/호스트 연락(0507-1354-2761)으로 진행.",
    "img": null,
    "alt": "MMC 카페 - 라이트 우드 톤의 커피 바와 디저트 진열대",
    "top": false
  },
  {
    "k": "twoshot_coffee",
    "name": "강남 대관 전문 카페 투샷 (TWOSHOT Coffee)",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "coffee",
    "addr": "서울특별시 강남구 강남대로 310 유니온센터 B121 / B121 Union Center, 310 Gangnam-daero, Yeoksam-dong, Gangnam-gu, Seoul",
    "cap": "<b>47</b>명 max (published by ShareIt host) — noted as smaller than the 50-200 target, listed for completeness",
    "flag": "dedicated",
    "link": "https://shareit.kr/venue/13985",
    "linkText": "강남 전체 대관 전문 카페 투샷 - 쉐어잇 대관 페이지",
    "email": null,
    "note": "역삼동 뱅뱅사거리 유니온센터 지하에 있는 순수 커피바. 평일 저녁(월-목 17-24시, 금 17시 이후 익일)·주말 종일 전체대관 전문으로, 8인 미팅실 별도 보유. 무료 wifi/빔프로젝터/대형보드판 제공이고 음료는 별도 주문 가능 — 47명 상한이라 50-200명 규모에는 다소 빠듯하지만 보조 공간으로는 적합.",
    "img": null,
    "alt": "카페 투샷 내부 - 유니온센터 지하 화이트톤 카페 공간",
    "top": false
  },
  {
    "k": "maru180_180_asan",
    "name": "MARU180 마루180 (Asan Nanum Foundation)",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "cowork",
    "addr": "서울특별시 강남구 역삼로 180 (Yeoksam-ro 180, Yeoksam-dong)",
    "cap": "<b>150</b>-200 (event hall, published)",
    "flag": "contact",
    "link": "https://asan-nanum.org/contact-us/",
    "linkText": "asan-nanum.org — MARU180 contact page (foundation lists address + events email)",
    "email": "maru180@asan-nanum.org",
    "note": "Right on the Yeoksam corridor at the Yeoksam-ro/Teheran-ro intersection. Free rental of the B1 event hall for startup/enterprise-spirit events per the foundation's rental policy — perfect fit for a bilingual tech-week hack/coffee day. The dedicated rental microsite (maru.org/eventhall) is JS-only and would not render for verification, so we link the verified foundation contact page instead.",
    "img": "https://asan-nanum.org/wp-content/themes/base/images/maru/banner_2.ba66ec4de7f0a11fd73f.jpeg",
    "alt": "MARU180 - B1 event hall, cowork-cafe plus rooftop, startup hub at old Yeoksam tax office junction",
    "top": true
  },
  {
    "k": "dreamplus_gangnam_hanwha",
    "name": "DREAMPLUS Gangnam 드림플러스 강남 (Hanwha Life Innovation Hub)",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "cowork",
    "addr": "서울특별시 서초구 강남대로 311, B1 (311 Gangnam-daero, Seocho-gu)",
    "cap": "<b>~200</b>(main event hall, published)",
    "flag": "dedicated",
    "link": "https://blog.naver.com/hanwhadreamplus/223154308068",
    "linkText": "Official Hanwha DreamPlus Naver blog — Gangnam event-hall rental announcement (verified fetch)",
    "email": "contact@dreamplus.asia",
    "note": "Main event hall with full stage, LED video wall, podium, mics/speakers included; explicitly suits hackathons and demo days per the rental brief. Walking distance of the Teheran-ro/Gangnam axis, adjacent to Gangnam Station. KakaoTalk inquiry channel also offered.",
    "img": "https://blogthumb.pstatic.net/MjAyMzA3MTJfMjM5/MDAxNjg5MTU1NzI2ODQ0.ZJ4V_E-fB48LSrnwco8jrK6o-GJNivDzO3hQUpUVnvsg.yPLmew3rLw8fhTEwFnvxpoEtvwey3km3KoF8xjfPzpsg.JPEG.hanwhadreamplus/IMG_4133.JPG?type=w2",
    "alt": "Main event hall at DreamPlus Gangnam, stage with LED video wall and 200-seat capacity",
    "top": false
  },
  {
    "k": "corea_conference_center",
    "name": "Corea Conference Center (COCOC) 한국컨퍼런스센터, by MyWorkspace",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "cowork",
    "addr": "서울특별시 서초구 강남대로53길 8 (8 Gangnam-daero 53-gil, Seocho-gu) — adjacent to MyWorkspace Gangnam Teheran-ro branch, 강남역 5번 출구 도보 2분",
    "cap": "<b>170</b>(auditorium, published) + conference rooms 30-54",
    "flag": "dedicated",
    "link": "https://www.cococ.kr/product/auditorium/",
    "linkText": "COCOC.kr — 대강당 (Auditorium) product page, 170-seat, specs and pricing",
    "email": null,
    "note": "Purpose-built conference floor with a 170-seat auditorium plus 30/54-seat breakout rooms — ideal for hack-day plenary plus side tracks. Per-hour pricing published (₩363,000/hr). Phones: 02-523-0303. KakaoTalk booking channel offered via MyWorkspace parent site.",
    "img": "https://www.cococ.kr/wp-content/uploads/2021/04/sel_STF6172-600x401.jpg",
    "alt": "COCOC auditorium stage with 250-inch screen, ceiling monitors, 170-seat theater layout",
    "top": false
  },
  {
    "k": "it_square_oakwood",
    "name": "IT Square 아이티스퀘어 (Oakwood Premier Coex Center)",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "cowork",
    "addr": "서울특별시 강남구 테헤란로87길 46 오크우드 코엑스센터 2F (46 Teheran-ro 87-gil, Gangnam-gu)",
    "cap": "<b>200</b>-300 (437 m², published on venue site; theater 250 per layout chart)",
    "flag": "dedicated",
    "link": "https://itsquare.co.kr",
    "linkText": "itsquare.co.kr — official venue page with rental specs, layouts, contact",
    "email": "itsquare@kakao.com",
    "note": "Directly on the Teheran-ro corridor, a 437 m² convention-style hall on the Oakwood Coex 2nd floor with 7m-wide front LED. Published rental process (inquiry → review → approval → event). Cafés and partner hotels nearby.",
    "img": "https://cdn.imweb.me/thumbnail/20250319/be5fd19a397c3.jpg",
    "alt": "IT Square main hall with large LED front wall and round-banquet layout, 200-300 capacity",
    "top": false
  },
  {
    "k": "spaceshare_gangnam_center",
    "name": "SPACESHARE Gangnam Center 스페이스쉐어 강남센터",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "cowork",
    "addr": "서울특별시 서초구 (Sinnonhyeon-area, 강남권) — 신논현역 2번 출구 동일빌딩",
    "cap": "Up to <b>200</b>(largest hall), 9 rooms total, 10-200 range",
    "flag": "dedicated",
    "link": "https://spaceshare.co.kr/centers/gangnam",
    "linkText": "spaceshare.co.kr/centers/gangnam — dedicated center page with capacity, phone, KakaoTalk",
    "email": null,
    "note": "Dedicated rental-only venue buffer south of the corridor (Sinnonhyeon, one stop south of Gangnam/신논현역). Largest hall fits 200; multiple mid-sized rooms useful for parallel hack-day tracks. Direct phones: 010-3262-7977 / 010-3256-7977.",
    "img": "https://spaceshare.co.kr/data/upload/MDAy.jpg",
    "alt": "SPACESHARE Gangnam 3F main room, 200-person classroom-style layout, modern lighting",
    "top": false
  },
  {
    "k": "dcamp_banks_foundation",
    "name": "D.CAMP 디캠프 선릉 (Banks Foundation for Young Entrepreneurs)",
    "area": "Gangnam (Teheran-ro / Yeoksam corridor)",
    "type": "cowork",
    "addr": "서울특별시 강남구 선릉로 551 새롬빌딩 2,4,5,6F (551 Seolleung-ro, Gangnam-gu)",
    "cap": "<b>150</b>-200 (multipurpose hall 6F, published in D.CAMP brochure)",
    "flag": "dedicated",
    "link": "https://dcamp.kr/program/space?tab=",
    "linkText": "dcamp.kr — 공간/Space program page (lobby, multipurpose hall, amenities)",
    "email": "contact@dcamp.kr",
    "note": "Startup-focused hub inside the Teheran-ro/Seolleung corridor with a 6F multipurpose hall (150-200 seat) plus terrace with Seonjeongneung views. Free/low-fee rental for ecosystem events; catering zone included.",
    "img": "https://s3-ap-northeast-2.amazonaws.com/dcamp-web-public/styles/max_650x650/s3-public/2026-07/L1260640%28%EC%9E%91%EC%97%85%EB%B3%B8%29.jpg?itok=_PMpbxb-",
    "alt": "D.CAMP 6F multipurpose hall with terrace overlooking Seonjeongneung royal tomb, invited demos and talks",
    "top": false
  },
  {
    "k": "seongsu_jiang_seongsu",
    "name": "Seongsu Jiang / Seongsu Jiang Cooperative (성수지앵협동조합)",
    "area": "Seongsu-dong (Seoul Forest east edge)",
    "type": "coffee",
    "addr": "101 Wangsimni-ro, Seongdong-gu, Seoul (서울특별시 성동구 왕십리로 101), 1F/2F cafe + 4F private workshop floor",
    "cap": "<b>4</b>-floor complex; 1F+2F large cafe floors plus 4F private workshop / party room — combined footprint well over 200 (est); each floor easily fits 50-80 seated",
    "flag": "dedicated",
    "link": "https://shareit.kr/store/4171",
    "linkText": "Share.it venue listing (Korean)",
    "email": null,
    "note": "4-floor complex steps from Seoul Forest Gate (Bundang Line Seoul Forest exit 5, ~290 m) with 1F/2F as a large cafe and a dedicated 4F workshop/party floor, so multi-track hack sessions and break-outs fit naturally. Wheelchair-accessible, two disabled parking bays; booking is via Naver / Kakao channel + 070-4156-7500 (Korean-only).",
    "img": "https://www.seouldanurim.net/comm/getImage?srvcId=MEDIA&parentSn=59181&fileTy=MEDIA&fileNo=1",
    "alt": "Wide interior shot of the Seongsu Jiang cafe floor on seouldanurim.net (official city accessibility listing)",
    "top": true
  },
  {
    "k": "cafe_onion_seongsu",
    "name": "Cafe Onion Seongsu (카페 어니언 성수)",
    "area": "Seongsu-dong (Seoul Forest east edge)",
    "type": "coffee",
    "addr": "8 Achasan-ro 9-gil, Seongsu-dong 2-ga, Seongdong-gu, Seoul 04797 (서울특별시 성동구 아차산로9길 8)",
    "cap": "<b>~200</b>(est) — sprawling renovated metal-factory, two interior halls + rooftop terrace; no published event capacity",
    "flag": "contact",
    "link": "https://m.onionkr.com/artfinger/offline.html?cate_no=26",
    "linkText": "Cafe Onion official store-contact page",
    "email": "onion@onionkr.com",
    "note": "Iconic 1970s factory retrofit with huge industrial interior, mezzanine and rooftop — very photogenic backdrop for a tech-week coffee day, and corp email published on the official contact page. No dedicated events page; you negotiate a partial or full buyout via onion@onionkr.com / store phone 070-4353-3238. Weekend crowds make weekday booking advisable.",
    "img": "https://english.visitseoul.net/comm/getImage?srvcId=MEDIA&parentSn=14422&fileTy=MEDIA&fileNo=1&thumbTy=L",
    "alt": "Wide shot of Cafe Onion Seongsu interior (Visit Seoul official)",
    "top": false
  },
  {
    "k": "grandpa_factory",
    "name": "Grandpa Factory (할아버지공장)",
    "area": "Seongsu-dong (Seoul Forest east edge)",
    "type": "coffee",
    "addr": "9 Seongsui-ro 7ga-gil, Seongdong-gu, Seoul (서울특별시 성동구 성수이로7가길 9)",
    "cap": "<b>~150</b>-200 (est) — 2 interior floors + treehouse courtyard + rooftop greenhouse; no published capacity",
    "flag": "contact",
    "link": "https://www.instagram.com/grandpa.factory",
    "linkText": "Grandpa Factory Instagram (Korean)",
    "email": null,
    "note": "Converted factory cafe used as a Vincenzo filming set, with group terrace seating, treehouse, and greenhouse-style rooftop — memorable for a hack-day crowd. Instagram bio lists a separate 대관 (rental) line 010-3934-2301 plus booking phone 02-6402-2301; booking is largely over Kakao/DM, no published email.",
    "img": "https://danielfooddiary.com/wp-content/uploads/2023/04/grandpafactorycafe1.JPG",
    "alt": "Wide Grandpa Factory Cafe interior (DanielFoodDiary)",
    "top": false
  },
  {
    "k": "daelim_changgo_gallery",
    "name": "Daelim Changgo Gallery (성수동 대림창고 갤러리)",
    "area": "Seongsu-dong (Seoul Forest east edge)",
    "type": "coffee",
    "addr": "78 Seongsui-ro, Seongsu-dong 2-ga, Seongdong-gu, Seoul 04784 (서울특별시 성동구 성수이로 78)",
    "cap": "<b>~150</b>-200 (est) — 1970s rice-mill building split into B/C/D halls plus cafe floor",
    "flag": "dedicated",
    "link": "https://www.popupkorea.co.kr/popup_store/728",
    "linkText": "Popup Korea venue listing for Daelim Changgo (Korean)",
    "email": null,
    "note": "Landmark red-brick rice-mill-turned-cafe-and-gallery that regularly runs brand pop-ups in its B/C/D halls, so event production is in-house muscle; cafe operates 11:00-22:00 daily and catering can ride on the on-site cafe. Book through Popup Korea listing — weekday event-hours also possible outside 12:00-20:00 with separate inquiry.",
    "img": "https://tong.visitkorea.or.kr/cms/resource/69/2721169_image2_1.jpg",
    "alt": "Wide Daelim Changgo Gallery interior (Korea Tourism Organization)",
    "top": false
  },
  {
    "k": "coffee_sigu_seongsu",
    "name": "Coffee Sigu Seongsu (커피식구 성수)",
    "area": "Seongsu-dong (Seoul Forest east edge)",
    "type": "coffee",
    "addr": "Seongdong-gu, Seoul — 8-min walk from Seongsu Stn Exit 2 (exact street address via Shareit booking flow)",
    "cap": "<b>40</b>seated with tables / 50 standing (published on Shareit)",
    "flag": "dedicated",
    "link": "https://shareit.kr/venue/11275",
    "linkText": "Share.it venue page (Korean)",
    "email": null,
    "note": "Dedicated rental cafe on a quiet Seongsu side-street with projector, wireless mic, speaker, free parking, host with multi-event experience — but published cap is 40-50, so it's only viable for a 50-person break-out / satellite session, not the full 100-200 hack day. Booking via ShareIT / Kakao channel @coffee.seekoo_seongsu.",
    "img": "https://img.shareit.kr/prod/img/2022-10-11/354256bb-1874-495e-92ee-f523fdf48cb1.jpg",
    "alt": "Wide hall interior of Coffee Sigu Seongsu (Shareit CDN)",
    "top": false
  },
  {
    "k": "sfactory_space_d",
    "name": "SFACTORY (에스팩토리) — SPACE [D]",
    "area": "Seongsu-dong (Seoul Forest east edge)",
    "type": "cowork",
    "addr": "서울특별시 성동구 연무장15길 11 (성수동2가 중심), Seoul 04783",
    "cap": "<b>~300</b>standing (est); published footprint 1F 570py + 3F 430py ≈ 3,300 sqm — comfortably absorbs 50–200 with room to spare",
    "flag": "dedicated",
    "link": "https://www.sfactory.co.kr/rental",
    "linkText": "에스팩토리 대관 / RENTAL (SPACE [D])",
    "email": "sfactory@level5.co.kr",
    "note": "Seongsu's largest dedicated event complex: red-brick converted factory, high ceilings, on-site cafe/tenants, bilingual-friendly operator. Ideal headline host for a 50–200 bilingual tech-week hack/coffee day; dedicated rental page lists direct email and weekday walk-throughs.",
    "img": "https://contents.sixshop.com/uploadedFiles/243585/default/image_1706235099324.jpg",
    "alt": "SFACTORY Space D interior - Seongsu's biggest event hall",
    "top": true
  },
  {
    "k": "hd_cafe_hongdae",
    "name": "HD Cafe (ㅎㄷ카페 / Hongdae Cafe)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "coffee",
    "addr": "서울 마포구 어울마당로 68 (68 Eoulmadang-ro, Mapo-gu, Seoul) — B1 through 9F",
    "cap": "<b>~200</b>(est; eight distinct floors each rented as one block, B1 performance stage + 9F rooftop)",
    "flag": "dedicated",
    "link": "https://www.popupkorea.co.kr/popup_store/542",
    "linkText": "PopUpKorea dedicated rental listing (HD Cafe full buy-out)",
    "email": null,
    "note": "Seoul's largest cafe complex — eight themed floors already wired for sound/LP/projection, so a bilingual hack day can split 50-200 across stage, gallery and rooftop without renting additional A/V. Visit Seoul tourism page and official Instagram @hongdae.cafe publish a rental phone line (010-8877-5497) separate from the cafe's main line.",
    "img": "https://korean.visitseoul.net/comm/getImage?srvcId=MEDIA&parentSn=71987&fileTy=MEDIA&fileNo=1&thumbTy=L",
    "alt": "HD Cafe (ㅎㄷ카페 / Hongdae Cafe) interior",
    "top": true
  },
  {
    "k": "teamplace_hongdae",
    "name": "TeamPlace (팀플레이스) Hongdae",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "coffee",
    "addr": "서울 마포구 월드컵북로4길 12 B1 SJ타워 (B1, 12 World Cup buk-ro 4-gil, Mapo-gu)",
    "cap": "<b>~100</b>(est; venue advertises 100평/~330㎡ floor, 8 breakout rooms plus large common lounge)",
    "flag": "dedicated",
    "link": "https://www.spacecloud.kr/space/1734",
    "linkText": "Spacecloud listing — Hongdae TeamPlace [workshops/events]",
    "email": null,
    "note": "Purpose-built for workshops and hack events — beam projector, sound, printing, free WiFi, and 8 curtained rooms around a big central lounge so one 100-person hack day can split into tracks; cafe on-site covers coffee. Phone 070-7797-7979, booking via Naver or Spacecloud.",
    "img": "https://mblogthumb-phinf.pstatic.net/MjAyMjAxMjBfMjA5/MDAxNjQyNjg5MzE2NDg4.gLetoFyu8ukrR1VXvyPmNKCY_7P5oHoMwZKq3PSo_3Ag.RXn3Qbf1smLgHEMW6UPzmTciMULLlxykKMzZGM_8GD8g.JPEG.xcocoa815/IMG_3150.jpg?type=w800",
    "alt": "Wide TeamPlace Hongdae lounge with 8 breakout rooms around common area, beam projector",
    "top": false
  },
  {
    "k": "catch_cafe_sinchon",
    "name": "Catch Cafe Sinchon (캐치카페 신촌)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "coffee",
    "addr": "서울 서대문구 연세로 8-1 버티고타워 5층 (5F Vertigo Tower, 8-1 Yonsei-ro, Seodaemun-gu)",
    "cap": "<b>~50</b>(est; venue publishes '30명 이상 = full rental' threshold, so 30-60 realistic)",
    "flag": "contact",
    "link": "https://m.blog.naver.com/palacej/222857052145",
    "linkText": "Official-cited blog walkthrough with rental tiers and contact phone",
    "email": null,
    "note": "Genuine specialty coffee shop run by Jinhak that explicitly does free whole-cafe buyouts for 30+ groups (and partial rentals 4-30) including beam/large screen/mic loan — perfect budget option for a bilingual tech-week coffee day. Book by phone 070-7760-7765 (Korean only) Mon-Fri.",
    "img": "https://mblogthumb-phinf.pstatic.net/MjAyMjA4MjJfMTAz/MDAxNjYxMTM5MDk4Nzg4.1EazsWxvrrXAz3zODqq2obINK4phkvPv1H3IeSBVYVEg._cHk4heub96tcy5_Xzla_Zg-miwK3l0BzF4w6NEsHdcg.JPEG.palacej/KakaoTalk_20220822_122228305_12.jpg?type=w800",
    "alt": "Catch Cafe Sinchon 5F panoramic interior",
    "top": false
  },
  {
    "k": "gongjon_multicultural_space",
    "name": "Gongjon (공존) Multi-Cultural Space Sinchon",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "coffee",
    "addr": "서울 서대문구 연세로5다길 46 2층 (2F, 46 Yonsei-ro 5da-gil, Seodaemun-gu)",
    "cap": "<b>~50</b>(est; venue page shows 21 guests fitting '넓게' comfortably, layout swaps to ~50)",
    "flag": "dedicated",
    "link": "https://pf.kakao.com/_PWAxbT",
    "linkText": "Official Kakao Channel home — booking is 100% reservation via KakaoTalk",
    "email": null,
    "note": "Sinchon's designated 복합문화공간 with beam screen, sound, sink + full kitchen zone — explicitly marketed for workshops, seminars and events; coffee is BYO/delivery so pair with a roastery partner. Booking channel is KakaoTalk only (no email/web form) — flag for international organizers.",
    "img": "https://mblogthumb-phinf.pstatic.net/MjAyMDEyMThfMzcg/MDAxNjA4MjY5MDk2ODA4.Z1OqkVtilJdDY3gqN8nU2qvreHH1fz16CJ3IRk9UTz0g.KMGqNvocaQu0TZNFzls9gCOuanwKOGaGF6IKhAjJVGgg.JPEG.heekyeung902/SE-2af6b665-1065-40f5-9fe3-37ef033e3801.jpg",
    "alt": "Gongjon Sinchon open hall with beam screen and flexible table layout",
    "top": false
  },
  {
    "k": "piknic_hongdae_gyeongui",
    "name": "Piknic Hongdae Gyeongui Line Forest (피크니크 홍대 경의선숲길점)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "coffee",
    "addr": "서울 마포구 서강로13길 24 1-2층 (24 Seogang-ro 13-gil, Mapo-gu) — same park block as the listed Seogang-ro 13-gil 22 rental",
    "cap": "<b>~80</b>(est; indoor 1F+2F each ~20평 plus 120평 lawn/yard and rooftop on request)",
    "flag": "contact",
    "link": "https://www.picniq.kr/shop",
    "linkText": "Official picniq site — Hongdae Gyeongui Line Forest branch info",
    "email": "picniqcafe@gmail.com",
    "note": "Working souffle-pancake cafe with a 120평 lawn inside Gyeongui Line Forest Park — a PopUpKorea listing for the same venue block (서강로13길 22) explicitly offers day-rate buy-out including F&B service and alcohol license, so a coffee hack day can spill onto the lawn. Chain head office handles bookings via picniqcafe@gmail.com.",
    "img": "https://mblogthumb-phinf.pstatic.net/MjAyNDEyMTdfMTU5/MDAxNzM0MzgzNzY1OTk2.AbooGb9Af3jpfpz4zdmq5j4OV0cmx95SEF7yRxqZjfog.kyJ7rDhlogL8iffSU1chhjvaVtunVUeWhUQ6wis6ynMg.JPEG/SE-AD83E7A9-A66C-4F33-AE00-BFE106FAD4B7.jpg",
    "alt": "Piknic Hongdae Gyeongui Line Forest (피크니크 홍대 경의선숲길점) interior",
    "top": false
  },
  {
    "k": "ryse_autograph_collection",
    "name": "RYSE, Autograph Collection (라이즈 오토그래프 컬렉션)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "cowork",
    "addr": "130 Yanghwa-ro, Mapo-gu, Seoul 04038 (서울 마포구 양화로 130)",
    "cap": "<b>200</b>(RYSE Space, theatre); Studios A/E 60 each",
    "flag": "dedicated",
    "link": "https://www.marriott.com/en-us/hotels/selsa-ryse-autograph-collection/events/",
    "linkText": "RYSE Events & Meetings page",
    "email": "info@rysehotel.co.kr",
    "note": "Design-forward Marriott property in the heart of Hongdae with 6 meeting rooms, 552 sqm total, LED walls and full AV+catering. Largest room (RYSE Space) seats 200 theatre / 130 banquet, dead-center for a bilingual tech-week coffee+hack day.",
    "img": "https://cache.marriott.com/content/dam/marriott-renditions/SELSA/selsa-meeting-7040-hor-wide.jpg",
    "alt": "RYSE Space event room with LED wall, Hongdae",
    "top": true
  },
  {
    "k": "ktg_ktg_sangsangmadang",
    "name": "KT&G 상상마당 홍대 (KT&G SangsangMadang Hongdae)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "cowork",
    "addr": "65 Eoulmadang-ro, Mapo-gu, Seoul (서울 마포구 어울마당로 65)",
    "cap": "Live Hall: <b>400</b>standing / ~189 seated; screens, stage, lighting",
    "flag": "dedicated",
    "link": "https://www.sangsangmadang.com/rental/list",
    "linkText": "SangsangMadang rental guide (대관안내)",
    "email": null,
    "note": "Iconic Hongdae culture complex with a basement Live Hall, galleries and classrooms; a dedicated rental desk (tel 02-330-6200) handles seminars and conferences. B2F Live Hall and 4F/5F academy rooms can be combined for hack-day plenary + workshop track.",
    "img": null,
    "alt": "KT&G SangsangMadang Hongdae building exterior and live hall",
    "top": false
  },
  {
    "k": "wework_hongdae",
    "name": "WeWork Hongdae (위워크 홍대)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "cowork",
    "addr": "147 Yanghwa-ro, Mapo-gu, Seoul (서울 마포구 양화로 147)",
    "cap": "<b>~100</b>-150 (est) in lounge/common event space; meeting rooms smaller",
    "flag": "contact",
    "link": "https://www.wework.com/ko-KR/buildings/hongdae--seoul",
    "linkText": "WeWork Hongdae building page (list event-space amenity)",
    "email": null,
    "note": "WeWork Hongdae sits on the Hongik University strip and lists a bookable 'Event Spaces' amenity plus community-team support. The standalone events-solutions URL returned 404, so book via the building page contact form; barista bar and common areas suit a bilingual coffee hack day.",
    "img": "https://cdn-images.wework.com/images/12BA114A-542C-11EC-92AF-0E6A5DC689CD/12ba114a-542c-11ec-92af-0e6a5dc689cd_0.jpg?width=1600",
    "alt": "WeWork Hongdae common lounge with barista bar",
    "top": false
  },
  {
    "k": "front1_by",
    "name": "프론트원 FRONT1 by 디캠프 - 박병원홀",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "cowork",
    "addr": "122 Mapo-daero, Mapo-gu, Seoul (서울 마포구 마포대로 122, 4-5층)",
    "cap": "박병원홀: <b>200</b>; 세미나실A 40 / B 30; conference room 20",
    "flag": "contact",
    "link": "https://dcamp.kr/program/space",
    "linkText": "dcamp space page (행사공간 대관)",
    "email": "venue@dcamp.kr",
    "note": "Dcamp-run startup campus near Gongdeok (5 min from Sinchon side of the belt) with the 5F Park Byoung-won Hall seating up to 200 plus AV, podium and 100-in screen. Startup-focused, English friendly, ideal for a 50-200 bilingual tech-week hack day; inquiries to venue@dcamp.kr.",
    "img": "https://dcamp.kr/images/og-image.jpg",
    "alt": "Front1 Park Byoung-won Hall seminar setup",
    "top": false
  },
  {
    "k": "ecc_ewha_ecc",
    "name": "ECC 삼성홀 (Ewha ECC Samsung Hall, 이화여대)",
    "area": "Sinchon / Hongdae (Mapo-Seodaemun university belt)",
    "type": "cowork",
    "addr": "52 Ewhayeodae-gil, Seodaemun-gu, Seoul — Ewha Campus Complex B4 (서울 서대문구 이화여대길 52 이화캠퍼스복합단지 지하4층)",
    "cap": "<b>702</b>seats (incl. 8 wheelchair); 405 sqm stage",
    "flag": "dedicated",
    "link": "https://samsunghall.ticketlink.co.kr",
    "linkText": "ECC Samsung Hall rental page (대관안내)",
    "email": "perform@ewha.ac.kr",
    "note": "Sincher Ewha campus landmark auditorium with 702 seats, full stage rig and a dedicated rental desk (tel 02-6380-4430, perform@ewha.ac.kr). Right in the Sinchon core; fits the 200-person upper bound with room to scale, and is a natural bilingual venue for university-week programming.",
    "img": "https://samsunghall.ticketlink.co.kr/img/kor/pc/img_main_hall.jpg",
    "alt": "ECC Samsung Hall auditorium interior",
    "top": false
  }
];
