// Page copy
const CONFIG = {
  kicker: "SF Tech Week · ComputeCafe",
  title: "SF Tech Week — Venue Options",
  subtitle: "Cafes, coffee shops, event spaces, and coworking across San Francisco's Tech Week core — " +
            "SoMa/2nd St, downtown, and the standouts beyond. Built for ~50–300 person events during " +
            "SF Tech Week (Oct 5–11, 2026). Links point to verified private-events pages or best booking contacts.",
  extraStat: { n: "Oct 5–11", l: "SF Tech Week 2026 dates" },
  footnotes: [
    "<b>Neighborhood analysis (SFTW 2025 data):</b> SoMa — including the 2nd St / South Park corridor and East Cut — hosted ~40% of last year's events, roughly 2× FiDi (#2). The \"SoMa near 2nd Street\" hypothesis is confirmed: a16z sits at 2nd & Townsend, South Park is VC row, Anthropic is at 500 Howard. Watch Jackson Square/FiDi — the fastest-rising cluster for VC dinner formats.",
    "<b>Gone or not bookable — don't route inquiries here:</b> Bespoke (Westfield) and Galvanize (44 Tehama) are closed; so are Blue Bottle Mint Plaza, Vega Coffee (Folsom St), and Bluestone Lane 685 Market. WeWork and Industrious SF locations have no public event-rental program, and South Park Commons is members-only — a partnership ask, not a rental.",
    "<b>Seed-venue corrections:</b> Motoring Coffee is at 1525 Union St (Cow Hollow), not Russian Hill. SOHN is in Dogpatch (2535 3rd St). TIAT is at 151 Powell (Union Square), not SoMa. Bluestone Lane has no 101 California or Levi's Plaza café — its real downtown trio is 55 2nd St, 227 Front St, and 420 Folsom. Corgi Cafe hosting is free (attendees buy café items, or you set an F&B budget).",
  ],
  provenance: "Researched & links verified Aug 6, 2026 · SF Tech Week 2026: Oct 5–11 (LA Tech Week follows Oct 12–18) · " +
              "Photos load from each venue's own website; a placeholder appears where no photo was published. " +
              "Capacities are published or estimated figures — confirm when booking.",
};

const TYPE_META = {
  coffee: { label: "Coffee & café", icon: "☕" },
  cowork: { label: "Coworking",     icon: "🏢" },
  event:  { label: "Event space",   icon: "✨" },
};

const VENUES = [
  // ---------- SOMA / 2ND ST ----------
  {k:"sightglass", name:"Sightglass Coffee", area:"SoMa / 2nd St", type:"coffee",
   addr:"270 7th St, San Francisco", lat:37.7770339, lng:-122.4084399, cap:"~<b>50–150</b> · two-story roastery (SF caps unpublished)",
   flag:"dedicated", link:"https://sightglasscoffee.com/pages/host-your-next-event-at-sightglass", linkText:"Events page", email:"events@sightglasscoffee.com",
   note:"The SoMa roastery flagship — working Probat roaster, open bar, upstairs community/training lab. Their Hollywood buyout runs 150; confirm SF numbers with the events team.",
   img:"https://sightglasscoffee.com/cdn/shop/files/Sightglass-7th-Street-Community.jpg", alt:"Sightglass 7th St community space"},
  {k:"delah", name:"Delah Coffee", area:"SoMa / 2nd St", type:"coffee",
   addr:"370 4th St, San Francisco", lat:37.7810491, lng:-122.4002187, cap:"~<b>50–100</b> · open 6am–11pm daily",
   flag:"contact", link:"https://delahcoffee.com/contact/", linkText:"Contact", email:"info@delahcoffee.com",
   note:"Big lounge-style Yemeni coffeehouse with the best hours in SoMa — the only café here that natively covers an all-day-into-evening format. Second location at 450 Sansome (FiDi).",
   img:null, alt:"Delah Coffee interior"},
  {k:"bluestone", name:"Bluestone Lane (3 downtown cafés)", area:"SoMa / 2nd St", type:"coffee",
   addr:"55 2nd St · 227 Front St · 420 Folsom St", cap:"~<b>40–70</b> per café · venue hire via TripleSeat",
   flag:"dedicated", link:"https://bluestonelane.com/private-events/", linkText:"Private events", email:null,
   note:"Polished Aussie cafés on the 2nd St corridor, FiDi, and East Cut (Avery Lane has the patio). Turnkey corporate-events program; each room suits ~50, not 150.",
   img:"https://bluestonelane.com/wp-content/uploads/2021/05/BL_Web_LocationImage_TheAvery02-1600x600.jpg", alt:"Bluestone Lane Avery Lane café and patio"},
  {k:"minna", name:"111 Minna Gallery", area:"SoMa / 2nd St", type:"event", top:true,
   addr:"111 Minna St, San Francisco", lat:37.7874657, lng:-122.3993218, cap:"<b>450</b> · 4,300 sq ft gallery + two bars",
   flag:"dedicated", link:"https://111minnagallery.com/booking/", linkText:"Booking", email:null,
   note:"Two decades of SF tech launch parties, two blocks off 2nd St. 16-ft ceilings, theater lighting, daily Red Door Coffee service — a proven all-day buyout. ☎ (415) 974-1719",
   img:"https://111minnagallery.com/wp-content/uploads/2025/02/111-Minna-Gallery-2nd-Street-Gallery-Crowd.jpeg", alt:"Event crowd inside 111 Minna Gallery"},
  {k:"dg717", name:"DG717 (Digital Garage)", area:"SoMa / 2nd St", type:"event",
   addr:"717 Market St, San Francisco", lat:37.7868575, lng:-122.4036416, cap:"<b>80</b> seated / <b>200</b> standing · $2.5k half-day, $5k full-day",
   flag:"contact", link:"https://dg717.com/spaces/", linkText:"Spaces + inquiry", email:null,
   note:"Digital Garage's longtime hackathon and pitch-event hall at Market & 3rd — flexible ground floor, projector + mics included, some of the best all-day value downtown.",
   img:"https://images.squarespace-cdn.com/content/v1/69f3b2388b24d50047412ff2/cf6f1f92-0b69-4ac2-977a-95c542f42ef0/christmas_2025-172.jpg", alt:"Event in the DG717 main hall"},
  {k:"spur", name:"SPUR Urban Center", area:"SoMa / 2nd St", type:"event",
   addr:"654 Mission St, San Francisco", lat:37.787196, lng:-122.4012427, cap:"Up to <b>425</b> · 3 floors, from $20k/12hr",
   flag:"dedicated", link:"https://www.spur.org/facilityrental", linkText:"Facility rental", email:null,
   note:"Full-building takeover option a block from 2nd St — penthouse patio, house AV included. Its FAQ literally has conference-week minimums (GDC, Disrupt, Dreamforce). ☎ (415) 781-8726",
   img:null, alt:"SPUR Urban Center"},
  {k:"cityview", name:"City View at Metreon", area:"SoMa / 2nd St", type:"event",
   addr:"135 Fourth St, San Francisco", cap:"<b>200–2,000</b> · 31k sq ft + terrace",
   flag:"dedicated", link:"https://www.cityviewmetreon.com/services-and-pricing", linkText:"Services & pricing", email:"cityviewsales@byskylight.com",
   note:"The big-format option: divisible floor, skyline glass, 11,000 sq ft outdoor terrace next to Moscone. Overkill under ~150; ideal for a flagship day.",
   img:null, alt:"City View at Metreon"},

  // ---------- EAST CUT / SALESFORCE PARK ----------
  {k:"salesforcepark", name:"Salesforce Park × Andytown", area:"East Cut / Salesforce Park", type:"event",
   addr:"Salesforce Transit Center rooftop (Beale–2nd St)", cap:"Central Lawn <b>150</b> ($6.5k base) · Wetlands <b>50</b> ($4.5k)",
   flag:"dedicated", link:"https://www.tjpa.org/node/6647", linkText:"Park rentals", email:"info@tjpa.org",
   note:"Outdoor rooftop-park events with Andytown's kiosk on-site for coffee (they also cater off-site). Book via TJPA: 21-day lead, COI required; free group-outing permit exists for casual 26–150. October weather risk.",
   img:"https://www.tjpa.org/files/styles/rectangle/public/images/2024-10/Central_Lawn5.jpg", alt:"Central Lawn at Salesforce Park"},

  // ---------- FIDI / JACKSON SQUARE ----------
  {k:"corgi", name:"Corgi Cafe", area:"FiDi / Jackson Square", type:"coffee", top:true,
   addr:"9 Claude Ln, San Francisco", lat:37.7584, lng:-122.4131, cap:"Café ~<b>50</b>; form takes <b>100+</b> (uses their upstairs) · FREE hosting",
   flag:"dedicated", link:"https://www.corgicafe.com/host", linkText:"Host with us", email:"cafe@corgi.insure",
   note:"SF's first 24/7 café, built for founders — no venue fee (attendees buy café items or you set an F&B budget), <12hr response. The only all-night option in town; pressure-test real headcount.",
   img:"https://mma.prnewswire.com/media/2905117/Corgi_24_7_Cafe.jpg", alt:"Corgi Cafe on Claude Lane"},
  {k:"andytown-kearny", name:"Andytown Coffee — 66 Kearny", area:"FiDi / Jackson Square", type:"coffee",
   addr:"66 Kearny St, San Francisco", cap:"~<b>50–60</b> · 2,200 sq ft, weekdays only",
   flag:"contact", link:"https://andytownsf.com/pages/events", linkText:"Events/catering", email:null,
   note:"Andytown's newest downtown café (opened spring 2026) — right-sized for a small takeover or as your event's coffee partner; they run off-site event coffee catering too.",
   img:null, alt:"Andytown 66 Kearny"},
  {k:"canopy", name:"Canopy — Jackson Square", area:"FiDi / Jackson Square", type:"cowork",
   addr:"595 Pacific Ave, San Francisco", cap:"~<b>50–100</b> · boutique receptions, 6am–10pm windows",
   flag:"dedicated", link:"https://www.canopy.space/book-an-event/", linkText:"Book an event", email:"membership@canopy.space",
   note:"Design-forward coworking in the neighborhood VCs are moving into — the right room for a polished salon or founder dinner. Also FiDi (353 Kearny) and Fillmore locations.",
   img:null, alt:"Canopy Jackson Square"},
  {k:"mindspace", name:"Mindspace — 575 Market", area:"FiDi / Jackson Square", type:"cowork",
   addr:"575 Market St, San Francisco", lat:37.7895414, lng:-122.4003752, cap:"~<b>50–100</b> · three bookable floors",
   flag:"dedicated", link:"https://www.mindspace.me/event-city/san-francisco/", linkText:"Events page", email:null,
   note:"Coworking floors bookable for offsites, panels, and pitch nights on mid-Market. ☎ (415) 982-9395",
   img:"https://www.mindspace.me/wp-content/uploads/2025/06/galelry-with-text-5.png", alt:"Mindspace SF event space"},

  // ---------- UNION SQ / MID-MARKET ----------
  {k:"frontier", name:"Frontier Tower", area:"Union Sq / Mid-Market", type:"cowork", top:true,
   addr:"995 Market St, San Francisco", lat:37.7822426, lng:-122.4099718, cap:"\"Spaceship\" <b>200</b> standing / <b>120</b> seated + sky lounge",
   flag:"contact", link:"https://frontiertower.io/events", linkText:"Events + contact", email:"support@frontiertower.io",
   note:"The 16-floor deep-tech \"vertical village\" — 50+ events a month, hackathons to robot fights. The most Tech Week-native venue in SF; multi-floor takeovers possible.",
   img:"https://frontiertower.io/office/space_1.webp", alt:"Frontier Tower interior"},
  {k:"tiat", name:"TIAT", area:"Union Sq / Mid-Market", type:"event",
   addr:"151 Powell St, San Francisco", lat:37.7861941, lng:-122.4081308, cap:"<b>150</b> standing / ~<b>35</b> seated · gallery floor",
   flag:"contact", link:"https://www.tiat.place/", linkText:"Site + contact", email:"email@tiat.place",
   note:"Nonprofit art×tech gallery (opened Nov 2025) that actively solicits event proposals — salons, demos, performances. Best evening-format room on this list; note it's Union Square, not SoMa.",
   img:"https://cdn.sfstation.com/wp-content/uploads/2025/11/IMG_2859.jpg", alt:"TIAT gallery interior"},
  {k:"convene", name:"Convene — 100 Stockton", area:"Union Sq / Mid-Market", type:"event",
   addr:"100 Stockton, San Francisco", lat:37.7875, lng:-122.4067, cap:"Up to <b>468</b> · 53k sq ft, 7 rooms, turnkey AV + catering",
   flag:"dedicated", link:"https://convene.com/locations/san-francisco/100-stockton/", linkText:"Venue page", email:null,
   note:"The plug-and-play conference option: staffing, AV, and catering in-house. The most polished (and priced-accordingly) way to run an all-day 100–300 program.",
   img:"https://images.ctfassets.net/rpinqlxtcitg/1Dz77MyvthFXwYGejOwVLA/6fe1bba7270367a0ab766cea61e87a78/100-stockton-4th-floor-gallery.webp", alt:"Convene 100 Stockton gallery space"},

  // ---------- FERRY BUILDING ----------
  {k:"shack15", name:"Shack15", area:"Ferry Building", type:"cowork", top:true,
   addr:"1 Ferry Building, Suite 201", cap:"<b>400</b> standing / <b>350</b> seated · entire 2nd floor",
   flag:"dedicated", link:"https://www.shack15.com/events", linkText:"Events page", email:"info@shack15.com",
   note:"SF's founder clubhouse, with Bay Bridge views — conferences, founder talks, LP days, live podcasts. The marquee non-SoMa option; books via PerfectVenue.",
   img:"https://images.squarespace-cdn.com/content/v1/6656358bbb9e8644fd94bfa1/1716925865207-DNDUSHCDPDIAEN051065/home+hero.png", alt:"Shack15 in the Ferry Building"},

  // ---------- BEYOND THE CORE ----------
  {k:"sohn", name:"SOHN", area:"Beyond the core", type:"coffee", top:true,
   addr:"2535 3rd St, San Francisco (Dogpatch)", lat:37.7573567, lng:-122.3880359, cap:"Up to <b>160</b> · café + gathering space",
   flag:"dedicated", link:"https://www.sohnsf.com/privateevents", linkText:"Private events", email:"hello@sohnsf.com",
   note:"Deuki Hong's Korean-American café built exactly for this: corporate events, late-night coworking sessions, full buyouts. The best pure coffee-venue match in the city.",
   img:"https://images.squarespace-cdn.com/content/v1/684047fe6e7f3956c21a071e/2e27a206-75ef-4399-89fb-d20e2e2a369e/Sohn+%26+TAAF-61.jpg", alt:"Event inside SOHN"},
  {k:"motoring", name:"Motoring Coffee / The Motoring Club", area:"Beyond the core", type:"coffee",
   addr:"1525 Union St, San Francisco (Cow Hollow)", cap:"<b>150</b> · 7,000 sq ft art-deco warehouse",
   flag:"dedicated", link:"https://themotoringclub.com/host-an-event", linkText:"Host an event", email:"hello@themotoringclub.com",
   note:"Café up front, car-club warehouse behind — rotating car displays, 20-ft bar, conference room. A memorable buyout with a built-in demo-floor vibe; books via TripleSeat.",
   img:"https://images.squarespace-cdn.com/content/v1/59b08988b07869a1bea88310/63d66b94-8d01-4332-ad58-01d305309950/Motoring+Coffee+Club+House_026.jpg", alt:"The Motoring Club clubhouse with cars"},
  {k:"pearl", name:"The Pearl", area:"Beyond the core", type:"event",
   addr:"601 19th St, San Francisco (Dogpatch)", lat:37.761528, lng:-122.3889859, cap:"Up to <b>800</b> across 3 levels + rooftop",
   flag:"dedicated", link:"https://www.thepearlsf.com/spaces", linkText:"Spaces", email:"info@thepearlsf.com",
   note:"Premium three-level venue with SF's best rooftop — main floor, mezzanine, and after-party built into one buyout. ☎ (415) 269-7171",
   img:"https://cdn.prod.website-files.com/65a4812aa633aa799a12bd1e/65d436eefb16aa901ae5584c_10740_MP_-12.jpg", alt:"The Pearl main floor"},
  {k:"grayarea", name:"Gray Area (Grand Theater)", area:"Beyond the core", type:"event",
   addr:"2665 Mission St, San Francisco", lat:37.7544062, lng:-122.4185113, cap:"Grand Theater <b>800</b> / <b>450</b> seated · Half Theater 400",
   flag:"dedicated", link:"https://grayarea.org/services/venue-rental/", linkText:"Venue rental", email:null,
   note:"Historic theater run by SF's art-and-technology institution — full AV rig, fiber, nonprofit discounts. The right stage for a keynote/screening-format day.",
   img:"https://grayarea.org/wp-content/uploads/2023/06/endofyou-openingnight.jpg", alt:"Opening night inside Gray Area's theater"},
];
