#!/usr/bin/env python3
"""Assemble a BrewVenue city page config from dry-run research artifacts + evidence log.

Enforces the anti-hallucination contract: any venue whose `link` has no
corresponding successful fetch in evidence.jsonl is DROPPED with a warning,
exactly as the plan requires. Output is an unsigned CONFIG and the venue array —
a human (or the verify+build step) supplies title/footnotes/provenance.

The research `closures` list may mix genuine closures with research discards
(cells use it for scope/fit drop notes too, marked "dropped:"). Only genuine
closures reach the public "Gone" footnote; discards are emitted as a JS comment
for the review card. Closure claims backed only by search snippets (no fetched
source URL in the evidence log) are annotated as unverified.

Usage:
    python3 scripts/assemble_city_config.py \\
        --research docs/pilots/toronto/research.json \\
        --evidence docs/pilots/toronto/evidence.jsonl \\
        --out docs/pilots/toronto/toronto_config.js \\
        --dry-run-label "DRY RUN — links verify-sampled, NOT fully verified"

research.json shape:
    {"venues": [...contributor venue objects...],
     "closures": ["name", ...],
     "neighborhood_analysis": "one-liner for the footnote"}
"""
import argparse
import datetime
import json
import re
import sys

DISCARD_RE = re.compile(r"\bdropped:\s", re.IGNORECASE)


def load_evidence(evidence_path):
    recs = []
    with open(evidence_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                recs.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return recs


def load_success_urls(recs):
    ok = set()
    for rec in recs:
        for u in rec.get("urls") or [rec.get("url")]:
            if u and rec.get("outcome") == "success":
                ok.add(u.rstrip("/"))
    return ok


def closure_has_fetched_source(claim, recs):
    """True if a successful *fetch* (real URL, not a search-snippet line)
    mentions the closed venue in its url or used_for. Token-based so
    "Roastery"/"The Roastery" and domain forms like darkhorseespresso.com match."""
    head = re.split(r"\s+[—\-]|\(", claim, maxsplit=1)[0]
    words = [w for w in re.findall(r"[a-z0-9']+", head.lower()) if w not in ("the", "a", "an")][:2]
    if not words:
        return False
    for rec in recs:
        if rec.get("outcome") != "success":
            continue
        url = rec.get("url") or ""
        if not url.startswith("http"):
            continue  # tavily_search: pseudo-URLs are discovery, not sources
        spaced = re.sub(r"[^a-z0-9']+", " ", (url + " " + (rec.get("used_for") or "")).lower())
        squashed = spaced.replace(" ", "")
        if all(w in spaced.split() or w in squashed for w in words):
            return True
    return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--research", required=True)
    ap.add_argument("--evidence", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--dry-run-label", default=None)
    a = ap.parse_args()

    research = json.load(open(a.research, encoding="utf-8"))
    evidence = load_evidence(a.evidence)
    ok_urls = load_success_urls(evidence)

    kept, dropped = [], []
    for v in research.get("venues", []):
        link = (v.get("link") or "").rstrip("/")
        if link and link in ok_urls:
            kept.append(v)
        else:
            dropped.append((v.get("name"), v.get("link")))

    today = datetime.date.today().isoformat()
    label = a.dry_run_label or ""
    cfg = []
    cfg.append("// Page copy — GENERATED by assemble_city_config.py, " + today)
    if label:
        cfg.append("// *** " + label + " ***")
    cfg.append("const CONFIG = {")
    cfg.append('  kicker: "Toronto · Venue Scout",')
    cfg.append('  title: "Toronto — Venue Options",')
    cfg.append('  subtitle: "Candidate cafes & cowork/event spaces for the Sep 29, 2026 Tech Week-style '
               'coffee event (~50–200 people). " +')
    cfg.append('            "' + (label + " — " if label else "") +
               'capacities are published or estimated; confirm when booking.",')
    cfg.append('  extraStat: { n: "Sep 29", l: "Toronto event date, 2026" },')
    cfg.append("  footnotes: [")
    if research.get("neighborhood_analysis"):
        cfg.append('    "<b>Neighborhood analysis:</b> ' +
                   research["neighborhood_analysis"].replace('"', '\\"') + '",')
    raw_closures = research.get("closures") or []
    discards = [c for c in raw_closures if DISCARD_RE.search(c)]
    closures = [c for c in raw_closures if not DISCARD_RE.search(c)]
    unverified = []
    annotated = []
    for c in closures:
        if closure_has_fetched_source(c, evidence):
            annotated.append(c)
        else:
            unverified.append(c)
            annotated.append(c + " [UNVERIFIED — search-snippet evidence only; fetch a source before publishing]")
    if annotated:
        cfg.append('    "<b>Gone / don\'t route inquiries here:</b> ' +
                   ", ".join(c.replace('"', '\\"') for c in annotated) + '",')
    cfg.append("  ],")
    cfg.append('  provenance: "Researched ' + today +
               ((" · " + label) if label else "") + '",')
    cfg.append("};")
    cfg.append("")
    cfg.append("const TYPE_META = {")
    cfg.append('  coffee: { label: "Coffee shop", icon: "☕" },')
    cfg.append('  cowork: { label: "Cowork/event", icon: "🏢" },')
    cfg.append("};")
    cfg.append("")
    if discards:
        cfg.append("// Discarded during research (scope/fit — NOT closures; for the review card, not the page):")
        for d in discards:
            cfg.append("//   " + d)
        cfg.append("")
    cfg.append("const VENUES = " + json.dumps(kept, indent=2, ensure_ascii=False) + ";")

    with open(a.out, "w", encoding="utf-8") as f:
        f.write("\n".join(cfg) + "\n")

    print(f"kept {len(kept)} venues with verified links → {a.out}")
    print(f"closures: {len(closures)} in footnote ({len(unverified)} unverified) · {len(discards)} discards kept as comments")
    for c in unverified:
        print(f"  UNVERIFIED closure (no fetched source in evidence log): {c[:80]}")
    if dropped:
        print(f"DROPPED {len(dropped)} (no successful fetch in evidence log):")
        for name, link in dropped:
            print(f"  - {name}: {link}")
    return 1 if dropped else 0  # nonzero exit if contract dropped anything


if __name__ == "__main__":
    sys.exit(main())
